### ISSUE TITLE
Enum injection

### ISSUE THREAD

**Issue by ivanjunckes** [eclipse/microprofile-jwt-auth#101]
Hi guys, 

These are the supported values:
java.lang.String
• java.lang.Long
• java.lang.Boolean
• java.util.Set<java.lang.String>
• javax.json.JsonValue.TRUE/FALSE
• javax.json.JsonString
• javax.json.JsonNumber
• javax.json.JsonArray
• javax.json.JsonObject

Shouldn't we also support Enum classes? Strings could be transformed to a Enum using valueOf if the injection point is an Enum class.

What do you guys think?

**Comment by dblevins** [comment]
We should have identical conversion capabilities as the Config API.  Last I checked they were something like the following:

 - `public TheType(String)` produce an instance using public string constructor on the type itself.
 - `public static TheType parse(String)` produce an instance using a static factory on the type itself.

There's an order of precedence and if I recall correctly at least one supported more static factory pattern.

**Comment by starksm64** [comment]
I think this makes sense.

**Comment by radcortez** [comment]
Related with https://github.com/eclipse/microprofile-jwt-auth/issues/114

**Comment by sberyozkin** [comment]
Is it a duplicate of #100 ?

**Comment by sberyozkin** [comment]
Hi @ivanjunckes all, copying your requirement to #100, to keep it all centralized in one place;
CC @dblevins, @radcortez 
thanks
