### ISSUE TITLE
Support for Compressed JWTs

### ISSUE THREAD

**Issue by dblevins** [eclipse/microprofile-jwt-auth#112]
JWTs with either Cookie-like data or many user roles can get quite large.  There are well established pattern for compressing the body and including that hint in the header:

 - https://tools.ietf.org/html/draft-ietf-jose-json-web-encryption-40#section-4.1.3

**Comment by sberyozkin** [comment]
Hi David, that only applies to JWE. Perhaps it should be managed at the pure HTTP level with GZIP, etc

**Comment by sberyozkin** [comment]
Hi David, @dblevins, let me close it for now, please reopen it if you feel we should still support it for the signed JWTs. Your link is valid and it can be transparently supported as part of the [JWE Encryption issue](https://github.com/eclipse/microprofile-jwt-auth/issues/58). So lets consider this issue be a valid but duplicate issue. Cheers
