### ISSUE TITLE
Configuration support for multiple token issuers

### ISSUE THREAD

**Issue by chunlongliang-ibm** [eclipse/microprofile-jwt-auth#115]
In trusted servers to server (n to 1) communications, the initiators can self-issue JWT to impersonate and vouch users. Each initiating server can be considered as a token issuer with its own signing key. The Microservice provider (token recipient) need configuration options to resolve the corresponding signature verification key for the issuer identified in JWT payload. We need somehow to support sets of configuration in stead of one set of 
{
mp.jwt.verify.publickey.location
mp.jwt.verify.publickey
mp.jwt.verify.issuer
}
The recipient can first map the "iss" in JWT to mp.jwt.verify.issuer, then find public key or key location to verify the token

**Comment by sberyozkin** [comment]
Should it be supported instead by recognizing that the JWS headers may include X509 certs - since these impersonating servers are trusted ?

**Comment by IrminAuwerda** [comment]
I would also request the feature to allow for multiple issuers. The reason for my use case is slightly different.

Our services get accessed by several completely different user groups. They have different logins on different security realms, all resulting in a JWT. As such the issuer for each of these user groups is different (auth.xxx/auth/realms/realm-1 vs auth.xxx/auth/realms/realm-2). Some user groups are intranet users comming from the intranet (auth.intranet/auth/..) some from the internet (auth.internet.com/auth/...).

As such we do need to support multiple issuers. The full URL is the issuer. The separate realms have their own key sets.

**Comment by sberyozkin** [comment]
Not sure if it is really in scope of MP JWT. Selecting a given MP JWT configuration set based on the request context (HTTP headers, token content) seems to be out of scope, at this moment of time at least IMHO

**Comment by sberyozkin** [comment]
I'm sorry but I'd like to close this issue. As I've suggested, IMHO it is out of scope for MP JWT as how to a given MP JWT configuration set is selected
