### ISSUE TITLE
TCK Challenge: PrimitiveInjectionTest not according to spec

### ISSUE THREAD

**Issue by tomas-langer** [eclipse/microprofile-jwt-auth#116]
The spec clearly lists the supported types for injection in section 7.1.2.
The supported types are:
```
 java.lang.String
• java.util.Set<java.lang.String>
• java.lang.Long
• java.lang.Boolean
• javax.json.JsonValue subtypes
• java.util.Optional wrapper of the above types.
• org.eclipse.microprofile.jwt.ClaimValue wrapper of the above types.
MP-JWT implementations are required to support injection of the claim values using any of these types.
```
There is no mention of support for primitive types (in the whole spec document).
Yet the PrimitiveInjectionTest explicitly tests that the implementation support injection into a primitive type "long".

The TCK test is not according to the specification and as such it should be removed.

**Comment by tomas-langer** [comment]
Version used: 1.1.1

**Comment by starksm64** [comment]
This test was added after a discussion in the final discussion of the 1.0 spec here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/microprofile/BTZw0TGVLY8/dYt7JPhxAgAJ

and this PR to define what RawTypes meant in section 7.1.2:
https://github.com/eclipse/microprofile-jwt-auth/pull/43

So RawTypes refers to the object and primitive types of the claim values. I have created #127 to clarify this.
