### ISSUE TITLE
Add mpJwt audiences configuration property via mpConfig

### ISSUE THREAD

**Issue by chunlongliang-ibm** [eclipse/microprofile-jwt-auth#121]
The audiences is a common claim in JWT. If JWT contains "aud", the recipient is required to verify the audiences. Current mpconfig have configurations to verify issuer and signature only, need address other verifiable claims.

**Comment by MikeEdgar** [comment]
+1

This relates to smallrye/smallrye-jwt#110 and loosely to #63. 

Suggested properties:
* Set/List of audiences -> `mp.jwt.verify.audiences` 
* Whether the `aud` claim is required -> `mp.jwt.verify.requireaud`

As mentioned in the first comment, for the second property, it may be better to instead introduce a general property to allow specification of a list of required claims.

**Comment by MikeEdgar** [comment]
I would suggest this issue be expanded to generally support claim verification in an extensible way. There was a great suggestion in the MP JWT 1.1 draft discussion proposing the following as a way to verify a particular claim:

> Using a `mp.jwt.verify.claim.*` namespace could potentially allow us use the Config API to list the properties under the `mp.jwt.verify.claim.` and have all sub entries processed as claims using the format:
>
> - `mp.jwt.verify.claim.<claim> = <regex>`

And also a way to list the claims that are required:
> - `mp.jwt.verify.claims.required=sub,iss,color,groups,name,age`

Are there any thoughts on solving this audience configuration issue more broadly?

**Comment by sberyozkin** [comment]
@MikeEdgar I propose we follow your original idea and add `mp.jwt.verify.audiences` (only without `s`) as it is a well known claim and introduce something more generic at some later stage.

 @chunlongliang-ibm Can you please create a PR ?

**Comment by chunlongliang-ibm** [comment]
I would like to propose that we add mp-config property "mp.jwt.verify.audiences", and accept multiple audiences in comma delimited format, like
mp.jwt.verify.audiences=audience1, audience2, audience3

To maintain back-compatibility, there is no default value  for mp.jwt.verify.audiences. If mp.jwt.verify.audiences is not configured, and JWT contains "aud", it is up to service to interpret the default behavior.

**Comment by sberyozkin** [comment]
@chunlongliang-ibm sounds good to me, can you please start working on a PR ? Thanks

@MikeEdgar I guess since `aud` is such a well known claim, it makes sense to have a dedicated property for it, expanding it to `audiences` (similarly to `iss`->`issuer`). I'm not sure now about the generic mechanism for the required claims, may be we can discuss the idea further in another issue ? Please open if you'd like, cheers
