### ISSUE TITLE
Support the cases where JWT token is not available in HTTP Authorization header

### ISSUE THREAD

**Issue by sberyozkin** [eclipse/microprofile-jwt-auth#126]
For example, it can be bundled instead within the application payload - in which case the JAX-RS service code will manually submit it to MP-JWT to validate. It might also let MP-JWT be used with the non-HTTP protocols.

Another option is the token coming in the different HTTP header

**Comment by masini** [comment]
Another use case is the use of httpOnly cookie to communicate in a safer way from a JavaScript public client and the Resource Server.

**Comment by chunlongliang-ibm** [comment]
If JWT is too big, it may not fit into one header, I do see case that token is send in two headers.

**Comment by sberyozkin** [comment]
I'd like to close this issue as a duplicate of #93.
@chunlongliang-ibm IMHO supporting the case of the token being split across multple headers is a bit too far for MP JWT :-)
