### ISSUE TITLE
Spec needs clarification around injection of primitive types

### ISSUE THREAD

**Issue by starksm64** [eclipse/microprofile-jwt-auth#127]
We just refer to RawTypes in section 7.1.2 but did not fully spell out the discussion around this we had here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/microprofile/BTZw0TGVLY8/dYt7JPhxAgAJ

The types section needs to be more explicit about primitive types.

**Comment by sberyozkin** [comment]
@starksm64 so it is just `long` and `boolean` we are talking about here, given the requirement to support `Long` and `Boolean` ?

**Comment by radcortez** [comment]
Any reason to not support int / Integer? JsonNumber supports it...

**Comment by sberyozkin** [comment]
@radcortez No idea why it was not supported but we can't get it in for `1.2`. Perhaps for 2.0..., thanks

**Comment by rdebusscher** [comment]
I guess the spec sticked to JSONValues due to the nature of the JWT.

We need to talk about converters also in the case we support primitives/POJOs etc ...

**Comment by radcortez** [comment]
There are some talks of starting a converter spec... right now is ridiculous because most of the specs needs this kind of behaviour, we can keep duplicating it.

**Comment by radcortez** [comment]
I think that at the very least, we should support the counterpart primitive types for `Long` and `Boolean`, since the wrapper type are officially supported. There is already TCK tests for it, so we just need to add the primitive type to the spec.

If we are ok with this, I can push a PR for it.

**Comment by radcortez** [comment]
Support for other primitive types / wrappers can be included in 2.0, but implementations are free to support them (no changes requires in the spec for it).

**Comment by sberyozkin** [comment]
@radcortez Hi Roberto, +1, lets just add `long` and `boolean` clarification for 1.2 and for 2.0 we'll try to support everything else. Please create a PR, cheers
