### ISSUE TITLE
Make dependency on servlet optional in TCK

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-jwt-auth#133]
The JWT spec specifies interoperability with the Servlet container. This is covered by the `ServletTest` test. The problem is that this test fails when the runtime doesn't support servlets and thus this test should be optional.

We could introduce a test profile to be used by implementations that also support servlets. When this profile is activated (for implementations that support servlets), the `ServletTest` would be executed with other TCK tests. If not, the test would be skipped.

Alternatively, the test suite could detect whether servlets are supported by the implementation under test and activate the test only if servlets are supported. This is even better solution because implementations that support servlets can't just disable the optional test on their own. But it's probably much harder to implement.

**Comment by sberyozkin** [comment]
@OndroMih Can you please consider a PR ? Having a profile seems like the simplest solution, though I believe it should be activated by default so that it would be up to the runtimes which don't support it to deactivate it

**Comment by sberyozkin** [comment]
@OndroMih If you will have time to contribute to this issue before `JWT 1.2` then we can indeed make it part of `JWT 1.2`, thanks

**Comment by sberyozkin** [comment]
I believe it was resolved by #323, if not please open a new issue in the JWT Bridge spec, thanks
