### ISSUE TITLE
Why does the TCK run tests that require EJBs?

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-jwt-auth#134]
What's the reason for there being tests requiring a container to implement EJB functionality when it's not a requirement for MicroProfile?

**Comment by rdebusscher** [comment]
I guess it has to do with the [Optional EJB container integration](https://github.com/eclipse/microprofile-jwt-auth/blob/master/spec/src/main/asciidoc/interoperability.asciidoc#recommendations-for-optional-container-integration) where a few requirements are defined for EJB container.

In the same section there is also mentioning about Servlet requirements although MP does not include servlets.

**Comment by kenfinnigan** [comment]
If that's the case, then the tests for anything "optional" should be in a separate TCK module/artifact

**Comment by kenfinnigan** [comment]
Going to close as there is a specific suite file to run them without EJBs
