### ISSUE TITLE
Don't put `microprofile-config.properties` in META-INF

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-jwt-auth#135]
Currently, there is a `microprofile-config.properties` file present within META-INF of the test module for the TCK.

This can cause issues as it's a valid location to be picked up on the classpath, and the test jar is needed to run the tests. It would be better if the file was in a different location and then added to the tests that require it present in the deployment

**Comment by sberyozkin** [comment]
#164 is correct but is not complete, I was pretty sure I did run a Quarkus TCK but apparently I've missed it, as I was experimenting at a time with the new TCK tests
