### ISSUE TITLE
Milestone for MP 3.3 release

### ISSUE THREAD

**Issue by ederks85** [eclipse/microprofile-jwt-auth#141]
As discussed in the MP Hangout at 12/10/2019, please create a Milestone for MP 3.3 that includes JWT Auth change for this release.

**Comment by sberyozkin** [comment]
@ederks85 Can you please close this issue and update #137 instead ? Thanks

**Comment by ederks85** [comment]
Yes, this seems to be a duplicate.

**Comment by ederks85** [comment]
@sberyozkin I see the pull request but can you please create a Milestone that includes this change in order to satisfy https://github.com/eclipse/microprofile/issues/153? Thanks!

**Comment by sberyozkin** [comment]
@ederks85 no problems, thanks...

**Comment by sberyozkin** [comment]
@ederks85 the PR is linked to the `3.3` milestone so let me close this issue again :-), reopen please if needed
