### ISSUE TITLE
Propagate JWT token automatically

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-jwt-auth#145]
MP JWT token is normally pushed as a http header. I think it makes sense to propagate this header to downstream microservices so that no manual push is required. MicroProfile Open Tracing can help with this. Thoughts?

**Comment by kenfinnigan** [comment]
Isn't that handled by MP REST Client?

I don't think MP JWT can handle propagating itself to whatever might be called. Also, automatic propagation raises issues with passing security credentials when it shouldn't, as opposed to an "opt-in" approach

**Comment by rdebusscher** [comment]
By defining a [ClientHeadersFactory](https://github.com/eclipse/microprofile-rest-client/blob/master/api/src/main/java/org/eclipse/microprofile/rest/client/ext/ClientHeadersFactory.java) this can be performed, so it can be defined with MP JWT spec itself.

But as Ken says, this should not be activated by default as the token can be used to authenticate during a call.

**Comment by sberyozkin** [comment]
The token propagation should be taken with some care and is out of scope for MP JWT IMHO. This is a realm of the token exchange protocol which has just been standardized at the RFC level, In general the direct propagation should be discouraged as it loses the original audience and possibly - scope claims

**Comment by sberyozkin** [comment]
MP Context Propagation perhaps can help as well when it is deemed acceptable

**Comment by Emily-Jiang** [comment]
I understand the potential risk of propagating the jwt token by default. If there is a way to opt in, it will be great.

**Comment by radcortez** [comment]
You can use `org.eclipse.microprofile.rest.client.propagateHeaders=Authorization` to automatically propagate the authorization header (or any other header) via MP REST Client. Isn't this enough?

**Comment by sberyozkin** [comment]
@Emily-Jiang Hi Emily - @radcortez's hint resolves this issue, do you agree ?

**Comment by sberyozkin** [comment]
Hi Emily, I'm sorry but I'm going to close it for now, IMHO it is important now to avoid the list of issues becoming stale and I'm not sure we will do anything specific about this issue for a while due to the support from MP RestClient and ContextPropagation :-). Don't hesitate to reopen if you disagree, cheers

**Comment by matheusdallrosa** [comment]
> You can use `org.eclipse.microprofile.rest.client.propagateHeaders=Authorization` to automatically propagate the authorization header (or any other header) via MP REST Client. Isn't this enough?

Is there a way to get a header programmatically?
This is needed when you are not using Rest Client : )
ATM I have a custom solution with ThreadLocals, but is not a code I want inside an application.
