### ISSUE TITLE
Support OIDC Relying Party / client mechanic

### ISSUE THREAD

**Issue by maxveit** [eclipse/microprofile-jwt-auth#151]
I have the use-case, of migrating an JEE application that uses e.g. JSP to provide a web-based front-end to the user, to Microprofile. Typically, these kinds of applications have been implementing authentication and authorization using a LDAP repository.

In a modernization to cloud-native, often the LDAP, at least for authentication, is being replaced by OIDC. Since we still have front-end code in the application, the service should act as a Relying Party / OIDC Client.

My ask is, if this could be supported by the Microprofile standard, probably within the jwt-auth. More specifically, I suggest to support the `Authorization Code Flow`, `Implicit Flow` and `Hybrid Code Flow` as defined here: https://openid.net/specs/openid-connect-core-1_0.html#Overview

**Comment by sberyozkin** [comment]
Hi @maxveit While it all makes sense, it is highly unlikely we'd take care of it at the MP JWT level as it would require providing a portable OIDC adapter implementation which is unrealistic in the medium term at least.
Sorry, I'm currently trying to keep the list to the minimum as it has been stale for a while, so I'm going to close this issue shortly. It will be reopened in due time if needed.
Thanks

**Comment by maxveit** [comment]
Hi @sberyozkin that sounds reasonable.

What do you think about standardizing the Id, Access and Refresh token and how they should be accessed in case they are used? Then the adapter implementation would still be up to the individual implementing party of the MP spec, but from a developer PoV the access to relevant tokens would be standardized.

**Comment by Emily-Jiang** [comment]
@sberyozkin I disagree. The issue board is to log requirements and the issue should not be closed because the team cannot do it in the short term. Besides artificially keeping the short list of issues does not make sense. If you cannot do it in the short term, you can file it to future. Personally, I think this issue is very valuable for end users. We should discuss to see how this can be fixed.

**Comment by rdebusscher** [comment]
Probably `Authorization Code Flow` makes sense, not the others (as MP is a backend framework)

**Comment by radcortez** [comment]
There was some discussion about bringing JSR-375 to align more with JWT here https://github.com/eclipse/microprofile-jwt-auth/issues/57.

@maxveit if you are on a server that supports both Jakarta and MP, maybe you can have a look into https://javaee.github.io/security-spec/ and see if you can implement a custom authentication mechanism that suits your needs. 

In theory, you should be able to use it to authenticate REST endpoints too. It seems that @rdebusscher even has a couple of demos with it:
https://github.com/rdebusscher/jsr375-examples
https://github.com/atbashEE/jsr375-extensions

**Comment by maxveit** [comment]
@radcortez thanks - I'm good on the server I am on currently, it provides the features I need. But I would like to not use proprietary app server classes where possible.

**Comment by radcortez** [comment]
Well, these are not proprietary. They are part of the Java EE (now Jakarta EE) APIs. The only proprietary thing would be your own implementations of those API's.

It might even be an opportunity to do some investigation work and figure out if these should be integrated with MP JWT to allow for custom authentication implementations.

**Comment by maxveit** [comment]
Should have been more accurate - I don't want to open up to Jakarta EE, I want to stick with Microprofile only. I like the lightweight that Microprofile has and don't want to go back to EE.

**Comment by radcortez** [comment]
Ah! That makes sense :)

Well in that case, you might be able to implement this in your end using a JAX-RS Filter. I believe most MP servers do it this way to implement JWT.

**Comment by rdebusscher** [comment]
Problem is that OAuth2/OpenIdConnect flows send redirects to the login page of the provider.  Not all clients will be capable of handling this.

**Comment by sberyozkin** [comment]
@maxveit Sure, but all of these flows you've mentioned are covered in OAuth2 and OIDC specs in particular. There is a ton of details there. Every proper OIDC adapter implementation requires a tight integration with the underlying HTTP mechanism. I honestly do not see what MP JWT, as a spec, can add to it, especially since it has not been designed to accept the OIDC produced tokens only. It is at the different level to MP JWT how the server is managing the token acquisition. We can try and do some CSRF recommendations when the cookies are involved, but it is hard to go any further here

**Comment by sberyozkin** [comment]
Hi All, let me close it for now - @maxveit thanks for the proposal, if you will have some concrete ideas on how to support the authorization code flow (lets start from the one which is highly recommended in most cases) in MP JWT, then please reopen.
