### ISSUE TITLE
update readme of repository

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-jwt-auth#152]
The readme says it is 'a proposal' in the Status section.

With JWT 1.1 out and preparing for JWT 1.2, I would say this is no longer a proposal but something real.

**Comment by sberyozkin** [comment]
Also the following warning is produced during the build:
```
asciidoctor: ERROR: README.adoc: line 89: only book doctypes can contain level 0 sections
[INFO] Rendered /home/sberyozkin/work/rh/microprofile/microprofile-jwt-auth/tck/README.adoc
```
