### ISSUE TITLE
Set up MP JWT Google forum

### ISSUE THREAD

**Issue by sberyozkin** [eclipse/microprofile-jwt-auth#173]
Hey @radcortez if you can find few cycles, please do it given your experience with setting the same for MP config, or describe what you did, I suppose it is a standard Google groups creating, but I'm not 100% sure
Cheers

**Comment by radcortez** [comment]
It yes, but since I don't have any permission on it, it was @Emily-Jiang that handled the request.

@Emily-Jiang can you let us know what you did?

**Comment by sberyozkin** [comment]
@radcortez Thanks
@Emily-Jiang Can you help us make MP JWT have its own forum :-) ?

**Comment by Emily-Jiang** [comment]
You can just create a google mailing list by following [this instruction](https://support.google.com/groups/answer/2464926?hl=en).

**Comment by sberyozkin** [comment]
Good to know we don't need to have some special permissions :-)

**Comment by Emily-Jiang** [comment]
You should use the naming convention microprofile-jwt-auth for your google group name.

**Comment by keilw** [comment]
Are you sure this is necessary and helpful for every single MP spec or attempt right now?
There are roughly 20 or so if you exclude the parent or sandbox (which could probably justify such kind of separate list a bit more) 
Plus why another google group, aren't there Eclipse mailing lists now or soon after the whole WG establishment, too?

**Comment by rdebusscher** [comment]
There was the suggestion on the Hangout meeting of Jan 6th 2021 to activate the GitHub discussions option for each spec.
