### ISSUE TITLE
Clarify ClaimValue in combination with @SessionScoped

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-jwt-auth#183]
Now that `ClaimValue` can be 'injected' into Application and Session scoped beans (See changes in spec doc in PR #180), the usage of SessionScoped beans can lead to exception as `ClaimValue` is not `Serializable`.

**Comment by rdebusscher** [comment]
Possible solutions

1. Keep the Deployment exception for SessionScoped beans (as Session scope doesn't make much sense in REST applications.
2. Explicitly indicate that construct like this

       @Inject
       @Claim(...)
       private ClaimValue<sometype> xyz;

can lead to Exceptions.

**Comment by sberyozkin** [comment]
@rdebusscher I'd just go for 1. Thanks

**Comment by sberyozkin** [comment]
@rdebusscher How about we just drop completely a reference to `SessionScoped` (option3) if you say it does not make much sense anyway to use them ?

**Comment by radcortez** [comment]
I would probably say to do 1, so users can be educated that they is not intended to work with `SessionScoped` :)

**Comment by sberyozkin** [comment]
@radcortez I don't really mind, though it would be simpler just to drop it. But if someone would like a TCK then let it be part of the full TCK run only, I'm only going to restore the text to do with SessionScoped.
