### ISSUE TITLE
Update gitignore 'build' exclusion

### ISSUE THREAD

**Issue by sberyozkin** [eclipse/microprofile-jwt-auth#192]
Hey @radcortez Are you working with Intellij by any chance ? `build` is excluded right now to eliminate some InteliJ build artifacts according to the comment, but it affects a package like `build`, I had to change from `build` to `builder` in the JWT generation PR.
Is it possible to make in more specific as opposed to just `build` ? Not urgent or critical...

**Comment by radcortez** [comment]
I am.

If I remember correctly, IntelliJ does not use a `build` folder for Maven based projects. At least, I don't remember ever seeing one, so I think we can remove it from the ignore list.
