### ISSUE TITLE
SmallRye Compatible Certification Request for MicroProfile JWT RBAC 1.2

### ISSUE THREAD

**Issue by sberyozkin** [eclipse/microprofile-jwt-auth#227]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  Red Hat

- [x] Product Name, Version and download URL (if applicable):<br/>
  [SmallRye JWT 3.0.0-RC1](https://repo1.maven.org/maven2/io/smallrye/smallrye-jwt/3.0.0-RC1/)

- [x] Specification Name, Version and download URL:<br/>
   MicroProfile JWT RBAC 1.2

- [x] Public URL of TCK Results Summary:<br/>
  https://github.com/smallrye/smallrye-jwt/actions/runs/401187578

- [x] Java runtime used to run the implementation:<br/>
  Java 8 and 11

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  GH Actions - Ubuntu

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kwsutter** [comment]
I find the [Actions output](https://github.com/smallrye/smallrye-jwt/actions/runs/401187578) for the TCK results hard to decipher...  For example, I can see that tests were run for both Java SE 8 and 11.  But, how many tests are part of the bucket, how many were executed, and how many were successful.  Where is that data?  

I'll trust you for this ballot.  I've had a similar question on another Spec that used Github Actions for testing, but I didn't post the question.  Thanks for your help.

**Comment by radcortez** [comment]
Do you notice the attached tck-report in the artifacts sections? That is just a zip file that you can download and see the TestNG report. Does that work for you?

**Comment by emecas** [comment]
@radcortez  @sberyozkin 

Regarding to tests, when I tried to build `3.0.0-RC1` locally using different environments, I faced an error about `PS256 is an unknown, unsupported or unavailable`

I'm wonder if there is any particular dependency outdated on my local, but I could not find an indication in the README file about prerequisites, special procedure, or additional parameters during the build. Neither in Actions' script more that Actions runs using JAVA_HOME_8.0.275_x64 and I have 1.8.0_112

Thanks 

```
[ERROR] testSignClaimsPS256(io.smallrye.jwt.build.JwtSignTest)  Time elapsed: 0.008 s  <<< ERROR!
io.smallrye.jwt.build.JwtSignatureException: SRJWT05012: Failure to create a signed JWT token: PS256 is an unknown, unsupported or unavailable alg algorithm (not one of [none, HS256, HS384, HS512, ES256, ES384, ES512, RS256, RS384, RS512]).
        at io.smallrye.jwt.build.JwtSignTest.testSignClaimsPS256(JwtSignTest.java:431)
Caused by: org.jose4j.lang.InvalidAlgorithmException: PS256 is an unknown, unsupported or unavailable alg algorithm (not one of [none, HS256, HS384, HS512, ES256, ES384, ES512, RS256, RS384, RS512]).
        at io.smallrye.jwt.build.JwtSignTest.testSignClaimsPS256(JwtSignTest.java:431)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   JwtSignTest.testSignClaimsPS256:431 � JwtSignature SRJWT05012: Failure to crea...
[INFO]
[ERROR] Tests run: 58, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for SmallRye: MicroProfile JWT Parent 3.0.0-RC1:
[INFO]
[INFO] SmallRye: MicroProfile JWT Parent .................. SUCCESS [  8.335 s]
[INFO] SmallRye: MicroProfile JWT - Implementation Parent . SUCCESS [  1.873 s]
[INFO] SmallRye: MicroProfile JWT Implementation Common ... SUCCESS [  8.024 s]
[INFO] SmallRye: MicroProfile JWT Build Implementation .... FAILURE [01:13 min]
[INFO] SmallRye: MicroProfile JWT Implementation .......... SKIPPED
[INFO] SmallRye: MicroProfile JWT - Testsuite Parent ...... SKIPPED
[INFO] SmallRye: MicroProfile JWT Basic Testsuite ......... SKIPPED
[INFO] SmallRye: MicroProfile JWT TCK ..................... SKIPPED
[INFO] Empty Release Project to Avoid Maven Bug ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by radcortez** [comment]
I believe you required a more recent JDK 8 version. Can you please try to update yours and run again?

**Comment by sberyozkin** [comment]
@emecas - `PS256` is not a required algorithm to support for `MP-JWT 1.2; but in either case, you need Java11 or install BouncyCastle and it might work, I think Jose4j will be able to translate `PS256` to `SHA256withRSAandMGF1`... But yeah; only `RS256`, `ES256` are required signature algorithms

**Comment by sberyozkin** [comment]
@emecas Actually, I looked more carefully at the stack trace, as Roberto said, for Java 8 the more recent Java8 edition should help; I'm running Java11 myself but obviously some backporting has been done in the latest Java8 as well.

**Comment by emecas** [comment]
Thanks @sberyozkin @radcortez 

I got eventual problems with Java 11, in a different part of the build process (`SmallRye: MicroProfile JWT TCK ..................... FAILURE`), but after some retries I got the `BUILD SUCCESS` message

Finally, I was able to build it locally upgrading to the following JDK versions:
 
 - Java8:  `openjdk-8u272-b10-x64`
 - Java11:   `openjdk-11.0.9.1-x64` and `jdk-11.0.1`

**Comment by radcortez** [comment]
> I got eventual problems with Java 11, in a different part of the build process (`SmallRye: MicroProfile JWT TCK ..................... FAILURE`), but after some retries I got the `BUILD SUCCESS` message
> 

Was the issue related with the JDK 11 version as well? Or something else?

**Comment by sberyozkin** [comment]
As I mentioned at https://github.com/smallrye/smallrye-jwt/issues/347, the `PS256` test is not related to MP JWT 1.2 and is only part of JWT builder API module, with this API not being a standard at the moment

**Comment by sberyozkin** [comment]
@emecas Looks like a transient JVM fork problem on Windows.

Also re the `PS256` test failure with the old Java 8, since we have also discussed it here, the fix is at https://github.com/smallrye/smallrye-jwt/pull/348 and will be rebased into 3.0.0 RC2 or final - but what is important and which has already been discussed above it is not related to Mp JWT TCK.

Thanks

**Comment by dblevins** [comment]
See the comments on https://github.com/eclipse/microprofile-open-api/issues/459#issuecomment-748362004 for ways we can improve the public TCK results summary.  This one at least mentions the spec name and version, which is a bit better.
