### ISSUE TITLE
security-role to group mapping not working as expected with auth-method MP-JWT

### ISSUE THREAD

**Issue by jitendrakalyan** [eclipse/microprofile-jwt-auth#242]
We have simple webapp with a couple of JSPs. we want to deploy it on open liberty server (MicroProfile) and do authentication and authorization using MP-JWT. The plan is to have Webseal authenticate the user and generate a JWT. The WebApp will verify the JWT is valid and provide access to resources based on groups claim. 

web.xml
===============================================================

`<login-config>` 
`<auth-method>MP-JWT</auth-method>` 

`<realm-name>MP-JWT</realm-name>`

`</login-config>` 

 `<security-role>`
    `<role-name>Role1</role-name>`
  `</security-role>`

  `<security-role>`
    `<role-name>Role2</role-name>`
  `</security-role>`

	<security-constraint>
		<web-resource-collection>
			<web-resource-name>HR Users</web-resource-name>
			<url-pattern>/page1.jsp</url-pattern>
			 <http-method>GET</http-method>
		</web-resource-collection>
		<auth-constraint>
			<description>HR users</description>
			<role-name>Role1</role-name>
		</auth-constraint>
	</security-constraint>
	
	<security-constraint>
		<web-resource-collection>
			<web-resource-name>Users</web-resource-name>
			<url-pattern>/page2.jsp</url-pattern>
			 <http-method>GET</http-method>
		</web-resource-collection>
		<auth-constraint>
			<description>users</description>
			<role-name>Role2</role-name>
		</auth-constraint>
	</security-constraint>
</web-app>

server.xml
===================================================================

    
  `  <featureManager>
       <feature>microProfile-4.0</feature>
		<feature>jsp-2.3</feature>
		 <feature>servlet-4.0</feature>
	    
		<feature>mpJwt-1.2</feature>
    </featureManager>`

  `<ssl id="defaultSSLConfig" trustDefaultCerts="true" />`
   `<keyStore id="defaultTrustStore" password="secret"/>`

    
  `  <httpEndpoint host="*" id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" />`

    
   ` <applicationManager autoExpand="true"/>`
    
  `  <jspEngine keepGenerated="true"/>`
  
 `  <mpJwt id="mp-jwt" mapToUserRegistry="false"/> `
   
  `<application type="war" contextRoot="JWTOL" location="JWTOL" id="JWTOL" name="JWTOL">
     <application-bnd>
            <security-role name="Role1">
                <group name="Group1" />
            </security-role>
			<security-role name="Role2">
                <group name="Group2" />
            </security-role>
        </application-bnd>
    </application> `

`<mpJWT userNameAttribute="upn" groupNameAttribute="groups"/> `

</server>

The server is not recognizing/acknowledging the security-role to group mapping in the server xml. Infact JWT authorization only works if  <application-bnd> is removed. Then it directly takes group claim matches it to the role configured in web.xml and authorizes access. I couldn't find anything in the documentation that points to any different configuration for role and group mapping. This is not a JAX-RS application. We are not using any annotations. It is simply a couple of JSPs. We want to test this out so we can proceed to migrate our legacy java webapp applications to open liberty server from WebSphere.

**Comment by sberyozkin** [comment]
@jitendrakalyan Can you please move this issue to the OpenLiberty project ?
CC @teddyjtorres @ayoho

**Comment by jitendrakalyan** [comment]
> @jitendrakalyan Can you please move this issue to the OpenLiberty project ?
> 
> CC @teddyjtorres @ayoho  

Hi, I opened an issue ok open liberty project and @teddyjtorres helped me with a solution. You can close this issue. I wasn't sure when I opened the issue if it was related to this project or open liberty. I apologize for opening the issue here.

**Comment by sberyozkin** [comment]
@jitendrakalyan No problems at all :-), thanks

**Comment by jitendrakalyan** [comment]
Link to to the issue in open liberty project where this issue resolution is posted.
https://github.com/OpenLiberty/open-liberty/issues/17096
