### ISSUE TITLE
Release this spec to be part of 5.0

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-jwt-auth#252]
- [x] Create release note 2.0 for the spec
- [x] Perform a release 2.0-RC1 off the branch jakarta91-branch to be included in MP 5.0

**Comment by Emily-Jiang** [comment]
@sberyozkin can you resolve this issue asap? Most of the specs have created release candidates. Please let me know if you need any help with this.

**Comment by sberyozkin** [comment]
@Emily-Jiang, can you clarify please, 
Do we really need the release note for `2.0` while we are releasing `2.0-RC1` ?
And what do you mean by `Perform a release 2.0-RC1 off the branch jakarta91-branch to be included in MP 5.0` - MP 5.0 will include the final `2.0` release ?
Also #257 has to be fixed for 2.0 - where do we record it, in this task ?

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang, can you clarify please,
> Do we really need the release note for `2.0` while we are releasing `2.0-RC1` ?
Yes, you need a release note in the spec. The release note is for releasing 2.0. `2.0-RC1` is the release candidate for 2.0. You should mention the 2.0 release. See an [example](https://download.eclipse.org/microprofile/staging/microprofile-config-3.0-RC4/microprofile-config-spec-3.0-RC4.html#release_notes_30) .
> And what do you mean by `Perform a release 2.0-RC1 off the branch jakarta91-branch to be included in MP 5.0` - MP 5.0 will include the final `2.0` release ?
> Also #257 has to be fixed for 2.0 - where do we record it, in this task ?
No need to mention #257. There is no user impact what so ever. Besides, it is just a check sytle, part of the consuming parent pom formatter. If you want, you can associate with the issue of consuming parent pom.xml. I am okay with the new style. If you want to fix it back, just put in the 2.0 milestone.

**Comment by sberyozkin** [comment]
@Emily-Jiang I think #257 will have to be fixed for 2.0 - it is just too messy to have a build producing a new format every time and it looks not good IMHO. I'll talk to Roberto about it. But for RC1 it is not a problem.

**Comment by sberyozkin** [comment]
@Emily-Jiang The staging repo is here, https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1507, will promote shortly

**Comment by sberyozkin** [comment]
@Emily-Jiang That was already promoted. But RC2 would definitely be needed (see #259) - not a problem for RC1 I'd say as I don't think anyone would be ready to run TCK with it straight away. This is a problem with doing a release without testing it works. RC2 will need to be tested that TCK works, etc for sure

**Comment by sberyozkin** [comment]
@Emily-Jiang We can do RC2 once #264 is merged

**Comment by sberyozkin** [comment]
@Emily-Jiang Forgot the licenses are missing, so we can go ahead once #264 is merged and Roberto helps to resolve #263

**Comment by sberyozkin** [comment]
@Emily-Jiang I believe it can now continue from the `master` branch, as opposed to having to pick up all the recent post `RC1` updates from `master` and get them into `jakarta91-branch`, right ?

**Comment by Emily-Jiang** [comment]
@sberyozkin that's fine.

**Comment by sberyozkin** [comment]
@Emily-Jiang I can do RC2 later today
