### ISSUE TITLE
Release MP JWT 1.2.2

### ISSUE THREAD

**Issue by sberyozkin** [eclipse/microprofile-jwt-auth#259]
Staging repo is here: https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1508

I'll do a quick test with it and promote then

**Comment by sberyozkin** [comment]
@Emily-Jiang @radcortez Something got broken in the way TCK is built and now  `microprofile-jwt-auth-tck-*-tests.jar` is not built - I have verified that it still works just before the point MP Parent 1.3 got introduced.

Compare https://repo1.maven.org/maven2/org/eclipse/microprofile/jwt/microprofile-jwt-auth-tck/1.2.1/

with

https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1508/org/eclipse/microprofile/jwt/microprofile-jwt-auth-tck/1.2.2/

So as far as 1.2.2 release is concerned I'll create a new branch and will cherry pick only jose4j and the TCK fix PRs

**Comment by sberyozkin** [comment]
@Emily-Jiang @radcortez 

I've done a new release from a new `1.2.2` branch
https://ci.eclipse.org/microprofile/view/Release/job/MicroProfile%20Releases/658/,
all worked, tag is available in GitHub, but staging repository is not available, can you check please, may be you can see it ?

**Comment by sberyozkin** [comment]
@Emily-Jiang @radcortez 

I've done a new release from a new `1.2.2` branch
https://ci.eclipse.org/microprofile/view/Release/job/MicroProfile%20Releases/658/,
all worked, tag is available in GitHub, but staging repository is not available, can you check please, may be you can see it ?

**Comment by Emily-Jiang** [comment]
@sberyozkin you should not use parent pom 2.1 for JWT 1.2.2 release as the dependencies in the version 2.1 of parent are Jakarta EE 9.1. You should use parent pom 1.3.

**Comment by sberyozkin** [comment]
@Emily-Jiang I did not use parent pom 2.1, I used 1.3 and it did not work, you can try it on the master

**Comment by sberyozkin** [comment]
@Emily-Jiang Can you give me a favor please and check if you see what the problem with the staging repo, see https://github.com/eclipse/microprofile-jwt-auth/issues/259#issuecomment-911769288 ?

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang @radcortez
> 
> I've done a new release from a new `1.2.2` branch
> https://ci.eclipse.org/microprofile/view/Release/job/MicroProfile%20Releases/658/,
> all worked, tag is available in GitHub, but staging repository is not available, can you check please, may be you can see it ?

I can't see it either. You might have to delete the tag and start again. I have not seen this issue before.

**Comment by Emily-Jiang** [comment]
@sberyozkin I looked at the build log. I think it did not connect to sonatype at all. No remote snapshot was created. Normally, you should see this:
```
[INFO] [INFO]  * Remote staging into staging profile ID "72ca920b8d0826"
[INFO] [INFO]  * Created staging repository with ID "orgeclipsemicroprofile-1507".
[INFO] [INFO]  * Uploading locally staged artifacts to profile org.eclipse.microprofile
[INFO] [INFO]  * Upload of locally staged artifacts finished.
[INFO] [INFO]  * Closing staging repository with ID "orgeclipsemicroprofile-1507".
```
But in the 1.2.2, it did not happen, as shown below.
```
[INFO] [INFO] Bulk deploying locally gathered artifacts from directory: 
[INFO] [INFO]  * Bulk deploying locally gathered snapshot artifacts to URL https://oss.sonatype.org/content/repositories/snapshots/
[INFO] [INFO]  * Bulk deploy of locally gathered snapshot artifacts finished.
```

**Comment by sberyozkin** [comment]
@Emily-Jiang Grand, I'll retry - I wonder if there was some temp conflict as I had to remove the broken 1.2.2 tag. I'll remove it now and will retry a release in a few hours, cheers

**Comment by sberyozkin** [comment]
Renamed the branch as well just in case to `mpjwt1.2.2`

**Comment by sberyozkin** [comment]
@Emily-Jiang Unfortunately it did not work again, 
https://ci.eclipse.org/microprofile/view/Release/job/MicroProfile%20Releases/659/ passed, github tag published, nothing in the staging repository.

I'm going to update the branch head, drop the tag, and then may be you can try to do a `1.2.2` release from the `mpjwt1.2.2` branch (`1.3-SNAPSHOT` is a snapshot value) tomorrow ? May be it will work for you.

Cheers

**Comment by Emily-Jiang** [comment]
@sberyozkin I was off on Friday. Do you still want to do the release for you? Is the branch `mpjwt1.2.2` ready to be released?

**Comment by sberyozkin** [comment]
@Emily-Jiang Np, let me try one more time, thanks

**Comment by sberyozkin** [comment]
Hi @Emily-Jiang and @radcortez, it worked this time (and the 2nd one I did on Fri also worked - it just took a long time for Nexus to show the staging repository which I now dropped).
But there is something broken in the 1.2.2 release,
https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1510

When running TCK in `smallrye-jwt` with a `1.2.2` version, I'm seeing 
```
SmallRyeJWTArchiveProcessor.java:[11,47] package org.jboss.shrinkwrap.resolver.api.maven does not exist
SmallRyeJWTArchiveProcessor.java:[42,35] cannot find symbol
[ERROR]   symbol:   variable Maven
```

But if I build the `mpjwt1.2.2` branch locally and test `smallrye-jwt` against this local build (MP JWT version is `1.3-SNAPSHOT`) in this case then all works, no compilation failures, TCK pass.

https://github.com/eclipse/microprofile-jwt-auth/tree/mpjwt1.2.2 has nothing but 2 TCK related fixes picked up from the master branch...

Can you spot what may be going wrong with this shrinkwrap dependency ?

**Comment by radcortez** [comment]
Let me have a look.

**Comment by Emily-Jiang** [comment]
@teddyjtorres can you try to run 1.2.2 tck against Open Liberty to see whether you can get it to pass?

**Comment by sberyozkin** [comment]
@Emily-Jiang @teddyjtorres My local Maven repository was broken, Roberto helped to verify it.

Teddy, indeed, please double check on your end, I'm planning to promote tomorrow

**Comment by sberyozkin** [comment]
@Emily-Jiang I'm not sure it is worth dropping a 1.2.2 tag and do another release just so that `tck/README.adoc` can refer to `1.2.2` as opposed to `1.2`, I'd postpone updating the doc till `1.2.3` if it happens and someone notices (no one has noticed it does not refer to 1.2.1 - I guess because the whole pom fragment example is not reusable). `1.2.2` addresses 2 concrete TCK issues and the fact this README.adoc is a bit stale does not minimize the actual value of 1.2.2...

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang I'm not sure it is worth dropping a 1.2.2 tag and do another release just so that `tck/README.adoc` can refer to `1.2.2` as opposed to `1.2`, I'd postpone updating the doc till `1.2.3` if it happens and someone notices (no one has noticed it does not refer to 1.2.1 - I guess because the whole pom fragment example is not reusable). `1.2.2` addresses 2 concrete TCK issues and the fact this README.adoc is a bit stale does not minimize the actual value of 1.2.2...

@sberyozkin I don't think it is worth redoing the release. It's a maintainence release anyway.

**Comment by sberyozkin** [comment]
@Emily-Jiang yes, makes sense. MP JWT 1.2.2 staging repository has been promoted - thanks

**Comment by Emily-Jiang** [comment]
@sberyozkin please go ahead to promote the build as we have tested this tck jar against open liberty. The reported Java 17 issue was fixed.
