### ISSUE TITLE
microprofile-jwt-auth-tck tests jar is no longer built

### ISSUE THREAD

**Issue by sberyozkin** [eclipse/microprofile-jwt-auth#261]
microprofile-jwt-auth-tck tests jar is no longer built, after an update to MP Parent 1.3 (so the problem started happening before upgrading it further to 2.1).
How to reproduce: 
- checkout the master branch at the commit preceding an update to the 1.3 parent and confirm the tests jar is built
- checkout the master branch at the commit updating it to the 1.3 parent and confirm no tests jar is built

Hi Roberto, @radcortez, I looked at `tck/pom.xml` changes related to the 1.3 parent update and did not see anything that could've affected it - the problem may be in the parent pom somewhere...

**Comment by radcortez** [comment]
I believe it never worked with the new parent POM. You need a specific configuration in the jar plugin to build the tests jar, which never existed in the parent POM.

Since this is specific to the JWT project, we can add it directly.
