### ISSUE TITLE
A few more issues with JWT 2.0 release

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-jwt-auth#263]
When I tried to do a fix on JWT master branch for attaching source jar for test dir, I noticed a few more issues:
1. In the past, a few profiles were defined in the tck pom.xml. Now, they were removed. I think the two profiles should be added back in as at least one of them were mentioned in READM.ADOC.
2. README.ADOC needs to be updated to mention JWT 2.0 as the current version mentions 1.2.
3. None of the license files were made to any of the jars in api or tck. I think this related to https://github.com/eclipse/microprofile-parent/issues/50.

**Comment by Emily-Jiang** [comment]
@sberyozkin can you take a look at the above issues?

**Comment by sberyozkin** [comment]
@radcortez Hey Roberto, PR where an update to MP 1.3 parent was made got the local licenses removed I believe, see #232, can you please give me a favor and check point 3 above ?

I can take care of points 1/2, will restore the [profiles section](https://github.com/eclipse/microprofile-jwt-auth/pull/232/files#diff-c7973ae892437cdc63d039ee91cf6d93bc035ba2f77d5cfaf8c326924b6ffa2dL255)

**Comment by radcortez** [comment]
Let me have a look.

**Comment by radcortez** [comment]
Are you verifying the license files by building locally? To change to the EF license files you need to run with `-Drelease.revision=Final`.

I've tried it and it works for me. Can anyone else confirm?

**Comment by sberyozkin** [comment]
@radcortez I've tried with and without `-Drelease.revision=Final` and I see `tck/target/licenses`containing `al-2.0  al-2.0.html  efsl-1.0.html  eftckl-1.0  eftckl-1.0.html` - did you mean something else ?

**Comment by sberyozkin** [comment]
Here is TCK RC1: https://repo1.maven.org/maven2/org/eclipse/microprofile/jwt/microprofile-jwt-auth-tck/2.0-RC1/

**Comment by Emily-Jiang** [comment]
> @radcortez I've tried with and without `-Drelease.revision=Final` and I see `tck/target/licenses`containing `al-2.0 al-2.0.html efsl-1.0.html eftckl-1.0 eftckl-1.0.html` - did you mean something else ?

Can you open the test and api javadoc jar and verify the license?

**Comment by radcortez** [comment]
> @radcortez I've tried with and without `-Drelease.revision=Final` and I see `tck/target/licenses`containing `al-2.0 al-2.0.html efsl-1.0.html eftckl-1.0 eftckl-1.0.html` - did you mean something else ?

Yes, all the htmls are copied, what changes is the link used in the javadoc, so you need to open the javadoc and check if the link is correct.

**Comment by radcortez** [comment]
> > @radcortez I've tried with and without `-Drelease.revision=Final` and I see `tck/target/licenses`containing `al-2.0 al-2.0.html efsl-1.0.html eftckl-1.0 eftckl-1.0.html` - did you mean something else ?
> 
> Can you open the test and api jar and verify the license? I checked again. The license files are not in the TCK jars. See this MP Fault Tolerance 2.0 TCK jar [here](https://download.eclipse.org/microprofile/microprofile-fault-tolerance-3.0/microprofile-fault-tolerance-tck-3.0.jar). You can see the EF license file is under META-INF folder. It was one of the requirements. @radcortez @sberyozkin

I've checked FT, and the issue is that you are missing the marked file (an empty tck file) in `src/main/resources/META-INF`.

**Comment by Emily-Jiang** [comment]
I did more digging and found out that the missing licenses are for all non-final releases. For non-final releases, the jars should use Apache v2 licenses @radcortez .

> I've checked FT, and the issue is that you are missing the marked file (an empty tck file) in src/main/resources/META-INF.

I will add the marker file for all of the rest specs. I think a few of them might have missed that marker.

**Comment by sberyozkin** [comment]
@radcortez @Emily-Jiang 

With `-Drelease.revision=Final` the `index.html` in the TCK (and also API) javadoc jar links to the EF license, without  `-Drelease.revision=Final` - to the AF one. This is correct I believe.

After copying https://github.com/eclipse/microprofile-fault-tolerance/tree/master/tck/src/main/licenses to MP JWT,  the TCK jar itself also contains `LICENSE` if `-Drelease.revision=Final` is used - but does not have it if `-Drelease.revision=Draft` is used - MP FT 4.0-RC2 does not have it either so it is consistent.

But API jar does not have `LICENSE` with or without `-Drelease.revision=Final`, even after copying `licenses` folder to `api/src/main`

**Comment by radcortez** [comment]
> But API jar does not have `LICENSE` with or without `-Drelease.revision=Final`, even after copying `licenses` folder to `api/src/main`

Yes, there is no action associated with a `LICENSE` and the API jar. The `LICENSE` needs to be placed in the `resources/META-INF` folder to be copied to the resulting jar if a LICENSE has to be included (this is standard behaviour of the jar plugin and not related with the settings of the parent pom).

From my understanding, the API jar just needs to ship with whatever `LICENSE` is present in the resources, no matter if it is `Draft` or `Final`. If you look into the contents of the jar pre-parent pom, it has the same behaviour.
