### ISSUE TITLE
Open Liberty 21.0.0.12-beta: MicroProfile JWT RBAC 2.0 RC2 Compatible Certification Request

### ISSUE THREAD

**Issue by teddyjtorres** [eclipse/microprofile-jwt-auth#269]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  IBM
- [x] Product Name, Version and download URL (if applicable):<br/>
  [Open Liberty 21.0.0.12-beta](https://github.com/OpenLiberty/open-liberty/releases/tag/gm-21.0.0.12-beta)
- [x] Specification Name, Version and download URL:<br/>
  MicroProfile Interoperable JWT RBAC 2.0 
- [x] (Optional) TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [MicroProfile Interoperable JWT RBAC 2.0 RC2 TCK result](https://openliberty.io/certifications/microprofile/5.0/mpjwt/2.0/21.0.0.12-beta-TCKResults.html)
- [x] Public URL of TCK Results Summary:<br/>
  [MicroProfile Interoperable JWT RBAC 2.0 RC2 TCK result](https://openliberty.io/certifications/microprofile/5.0/mpjwt/2.0/21.0.0.12-beta-TCKResults.html)
- [x] Any Additional Specification Certification Requirements:<br/>
  Not applicable
- [x] Java runtime used to run the implementation:<br/>
  Java 8 and 11
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  RHEL 8
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by sberyozkin** [comment]
@teddyjtorres, @Emily-Jiang   Should this CCR be created against yet to be staged MP JWT 2.0 ?

**Comment by Emily-Jiang** [comment]
This CCR is for the latest RC, which is the identical to the staged JWT 2.0 to workaround the chicken egg problem.

**Comment by kwsutter** [comment]
Why does the reference to the TCK Version show a link to the TCK Results?
```
(Optional) TCK Version, digital SHA-256 fingerprint and download URL:
MicroProfile Interoperable JWT RBAC 2.0 RC2 TCK result
```

**Comment by kwsutter** [comment]
> This CCR is for the latest RC, which is the identical to the staged JWT 2.0 to workaround the chicken egg problem.

But, I think the CCR should still reference the final 2.0 Specification.  Maybe this update can or should be done after the vote is completed, but it looks odd to reference a preliminary version of the Specification for the final TCK results.

**Comment by kwsutter** [comment]
Also, like my other comments on the various CCRs, I think you should specific the specifics of the Java 8 and 11 runtimes that were used to certify.

**Comment by Emily-Jiang** [comment]
@kwsutter please see the comments from @radcortez and me regarding the CCR requirements [here](https://github.com/eclipse/microprofile-config/issues/725)

**Comment by sberyozkin** [comment]
Hi @teddyjtorres, @ayoho, @Emily-Jiang  I'm closing it now, I believe it has been resolved :-)

Happy Christmas and New Year
