### ISSUE TITLE
Stage the final release of JWT 2.0

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-jwt-auth#270]
Please update the dependency to Config 2.0 and then release the final version of JWT 2.0.

**Comment by sberyozkin** [comment]
@Emily-Jiang Did you mean 3.0 ? I've asked in the MP JWT chat; it does not pull it from Central so is it expected the master branch will fail ?

**Comment by sberyozkin** [comment]
@Emily-Jiang It has been staged to https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1539
