### ISSUE TITLE
License files are missing on some artifacts

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-jwt-auth#275]
The following jars have no license files attached:
microprofile-jwt-auth-tck-2.0-test-javadoc.jar 
microprofile-jwt-auth-tck-2.0-test-sources.jar
microprofile-jwt-auth-tck-2.0-tests.jar

I think the Javadoc jar should have EF license while the -sources and -tests jars should have Apache V2 license as they only contain source files.

**Comment by radcortez** [comment]
I've updated the Parent POM to place the EF License files on the Final release. The Apache files still need to be added manually.

**Comment by Emily-Jiang** [comment]
@sberyozkin for javadoc one it should be EF license and the -sources and -tests need to add Apache License.

**Comment by radcortez** [comment]
Are we sure that it needs to be Apache LICENSE for `Final`? Right now all the binaries coming from the TCK on `Final` use the EF TCK License.

**Comment by Emily-Jiang** [comment]
For a final release, IIRC, api jar and source files, I think we need Apache licenses. For tck jar, spec doc, all of the javadoc jars, we need EF licenses. @kwsutter can you confirm?

**Comment by radcortez** [comment]
Ok, let me try to summarize what we are doing right now to make sure that we are doing the right thing or if we need to change something.

For a `Draft` release:

We don't touch any LICENSE file. Whatever LICENSE file is present in the sources ends up in the resulting binaries. Remember that a LICENSE file in `main` sources will only end in the main binaries (jar, javadocs and sources). If a LICENSE file is also needed for `test` binaries, the file needs to be included manually in the `test` sources (so it is also included in test-jar, test-sources and test-javadoc). I can probably add a profile to copy the LICENSE from `main` to `test` if required.

For a `Final` release:

- We don't touch the LICENSE file in the `api` module for the resulting `jar` and `sources`, so it ends up with the current LICENSE (usually ALv2)
- We replace the `javadoc` LICENSE with the EFSL in the `api` module.
- We don't touch the LICENSE in the `spec` module (pdf and html). Usually, it is already set to be the EFSL, even for a `Draft` Release.
- We replace all LICENSES in the `tck` module with the EFTCKL for all binaries (jar, sources, javadoc, test-jar, test-sources  and test-javadoc).

**Comment by Emily-Jiang** [comment]
> Ok, let me try to summarize what we are doing right now to make sure that we are doing the right thing or if we need to change something.
> 
> For a `Draft` release:
> 
> We don't touch any LICENSE file. Whatever LICENSE file is present in the sources ends up in the resulting binaries. Remember that a LICENSE file in `main` sources will only end in the main binaries (jar, javadocs and sources). If a LICENSE file is also needed for `test` binaries, the file needs to be included manually in the `test` sources (so it is also included in test-jar, test-sources and test-javadoc). I can probably add a profile to copy the LICENSE from `main` to `test` if required.
> 
> For a `Final` release:
> 
>     * We don't touch the LICENSE file in the `api` module for the resulting `jar` and `sources`, so it ends up with the current LICENSE (usually ALv2)
> 
>     * We replace the `javadoc` LICENSE with the EFSL in the `api` module.
> 
>     * We don't touch the LICENSE in the `spec` module (pdf and html). Usually, it is already set to be the EFSL, even for a `Draft` Release.
> 
Agree with the above statements.
>     * We replace all LICENSES in the `tck` module with the EFTCKL for all binaries (`jar`, `sources`, `javadoc`, `test-jar`, `test-sources` and `test-javadoc`).
The `sources` and `test-sources` jars are in Apache v2 while the other tck jars should have EFTCKL. I double checked with @kwsutter and he confirmed this.

**Comment by radcortez** [comment]
Ok, I need to adjust the Parent POM for it.
