### ISSUE TITLE
Remove target from Claim

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-jwt-auth#28]
For better reuse in many use cases (beyond whats defined in MP) it would be good if Claim did not specify a target, which would allow implementations more freedom on where users could put the claim.

**Comment by Emily-Jiang** [comment]
If it does not specify target, we need to support all targets. I think it is better to list the targets we support in 1.0. It is fine to add more targets in 1.1, which is still backward compatible.

**Comment by johnament** [comment]
I don't believe that's a requirement.  The spec should be clear on where you can use it as a part of MP.  However, it shouldn't preclude using it in other places.

https://github.com/eclipse/microprofile-health/pull/70 for a related issue in Health spec.

**Comment by johnament** [comment]
At a minimum we need to support the elements mentioned in config property

`@Target({ElementType.METHOD, ElementType.FIELD, ElementType.PARAMETER, ElementType.TYPE})`

**Comment by starksm64** [comment]
That is the current list of targets, so for 1.0, let's stick with that and define how it applies to other scopes for 1.1.

**Comment by johnament** [comment]
@starksm64 that's not the current list of targets.  https://github.com/eclipse/microprofile-jwt-auth/blob/master/api/src/main/java/org/eclipse/microprofile/jwt/Claim.java#L34

We need to add `TYPE` to that list.
