### ISSUE TITLE
Unauthorized response on a unprotected Endpoint, when a token is sent

### ISSUE THREAD

**Issue by fschuerer** [eclipse/microprofile-jwt-auth#282]
Hi,

I am using payara with mp-jwt.

My REST service has one unprotected endpoint. I want to forward a different JWT to another service. However this is not possible, due to the fact that the JWT will be validated by a non fitting publickey and issuer, although the endpoint is not protected.
Why it is necessary to validate the JWT for unprotected endpoints ?

Thnx
Frank

**Comment by sberyozkin** [comment]
Hi @fschuerer, as far as MP JWT is concerned, the token sent to the public endpoint has to be verified only if the endpoint has this token injected, see https://github.com/eclipse/microprofile-jwt-auth/blob/master/spec/src/main/asciidoc/interoperability.asciidoc#injection-of-jsonwebtoken

Please move this issue to the the Payara repository
thanks

**Comment by fschuerer** [comment]
Hi @sberyozkin,

thanks for your support. I created an [issue](https://github.com/payara/Payara/issues/5582) at the Payara repository.

**Comment by sberyozkin** [comment]
@fschuerer thanks
