### ISSUE TITLE
RolesAllowedSignEncryptTest.callEchoSignToken TCK test challenge

### ISSUE THREAD

**Issue by Verdent** [eclipse/microprofile-jwt-auth#297]
Hi,
I would like to ask, why is it expected for [this](https://github.com/eclipse/microprofile-jwt-auth/blob/09ba972d86498a4e20db569bd9d9627534123126/tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/jwe/RolesAllowedSignEncryptTest.java#L194) test to pass?

This is how I understand it:
1. Public key for signature verification is provided over the createDeployment() method
2. JWT is signed with private key in the test and it is sent to the test endpoint
3. During validation process we extract kid and alg from signed JWT headers
4. There is no public key for verification which would be bound to corresponding kid, so we fall back to the provided public key in the step one.
5. Validation passes and test fails.

What am I getting incorrectly here?

For example test [EmptyTokenTest.validToken](https://github.com/eclipse/microprofile-jwt-auth/blob/2e7611284bd722be3db70fa3867c93efcaa1e4b9/tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/EmptyTokenTest.java#L99) does exactly the same thing in terms of not having any public key provided to the kid and this time validation is expected to pass.

If we would not fall back to the public key which had not kid assigned, the first mentioned test would pass, but the second would fail.

**Comment by sberyozkin** [comment]
Hi @Verdent The reason the failure is expected is that the test endpoint expects a inner-signed encrypted token - so the successful verification is not enough - the token has to be decrypted first - however the test sends a signed only token.

**Comment by sberyozkin** [comment]
We'll need to discuss the dynamic token verification in more detail for 3.0, hopefully in scope of the multi-tenant support

**Comment by Verdent** [comment]
@sberyozkin Thank you for clarification. I have completely missed that. :-)

Closing issue
