### ISSUE TITLE
Release MP JWT 2.1 Final

### ISSUE THREAD

**Issue by sberyozkin** [eclipse/microprofile-jwt-auth#304]
CC @teddyjtorres, @dblevins @rdebusscher  - are we OK to go with the final Release ? What is the deadline for the final release ? CC @radcortez @Emily-Jiang

**Comment by Emily-Jiang** [comment]
@sberyozkin you need to have the final RC either today or tomorrow so that Open Liberty have time to consume it in the next beta. Otherwise, JWT 2.1 will need to end up in the next MP release.

**Comment by rdebusscher** [comment]
@sberyozkin 

I did not look into detail, but do we have a TCK test that fails when token is using _RSA-OAEP-256_ and no `mp.jwt.decrypt.key.algorithm` value is specified (so default is _RSA-OAEP_)

This makes sure that applications that are upgraded (and people don't update their config) suddenly aren't accepting tokens that are encoded with other algorithm.

**Comment by rdebusscher** [comment]
@Emily-Jiang 

You mean `need to have the final RC either today or tomorrow to be included in MicroProfile 6.0`. I cannot believe that the release cycle of an implementation decides if something will be in a release of MP or not. That would make MicroProfile no longer vendor neutral but owned by OpenLiberty team.

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang
> 
> You mean `need to have the final RC either today or tomorrow to be included in MicroProfile 6.0`. I cannot believe that the release cycle of an implementation decides if something will be in a release of MP or not. That would make MicroProfile no longer vendor neutral but owned by OpenLiberty team.

@rdebusscher MP 6.0 uses Open Liberty as the compatible implication in or der to get released. In order to release MP 6.0 in November, the specs need to get their final RC to be in the beta image of Liberty so that a ballot can be started with it. It's fine for JWT team not to board this train, it will mean 1.2 version will not be included in MP 6.0.

**Comment by sberyozkin** [comment]
@Emily-Jiang I'll release it today, as I wanted to wait till the call today to avoid any confusion re the technical discussion we are having with @dblevins.

**Comment by sberyozkin** [comment]
@Emily-Jiang By the way, can you please update Teddy on how to do the release in Jenkins, it should def not depend only on me doing the MP JWT releases.

**Comment by sberyozkin** [comment]
@Emily-Jiang 
>Unfortunatelly only MP committers can do the Jenkins release. Teddy is not a MP committer as yet.

That needs to be fixed as Teddy has been contributing to the calls for the last while, and he contributed with several patches.
Can you please remind how to start a nomination ? We can tall in the gitter if you'd like

**Comment by sberyozkin** [comment]
@Emily-Jiang 

>By the way, I posted a gitter message to say that I have done a release candidate for JWT. The next release will be staging Final release if you don't need to do any more RCx.
Thanks, well, unless there will be objections then I'd go for staging 2.1.Final next, otherwise we'll never make it to 3.0, going directly to 3.0 would be a problem

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang
> 
> > Unfortunatelly only MP committers can do the Jenkins release. Teddy is not a MP committer as yet.
> 
> That needs to be fixed as Teddy has been contributing to the calls for the last while, and he contributed with several patches. Can you please remind how to start a nomination ? We can talk in the gitter if you'd like

You can nominate MP committers from [here](https://projects.eclipse.org/projects/technology.microprofile/nominate/CM). By the way, you need to log on first to be able to see the form. We can talk on gitter if you hit any issues.

**Comment by sberyozkin** [comment]
Hi @Emily-Jiang  @teddyjtorres I think all is ready now for MP JWT 2.1 Final, but since we have merged PRs from David @dblevins and Teddy, we should drop the staged final release and re-stage it, Emily, can you please re-stage ?

**Comment by Emily-Jiang** [comment]
JWT 2.1 was released and this issue can be closed.

**Comment by sberyozkin** [comment]
@Emily-Jiang @teddyjtorres @dblevins Thank you, happy holidays to everyone
