### ISSUE TITLE
The release review comment from Jan

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-jwt-auth#313]
There is an open regression from the MP 5.0 review that he naming of the spec is highly inconsistent, details can be found in this issue: https://github.com/eclipse/microprofile-jwt-auth/issues/303
As this is a minor release and some of the required fixes may require a major release, none of the deviations are addressed yet (not even the simple ones).

Hope we could fix this and get a Jakarta EE 10 Core Profile based release then, that ensures testing of the component spec is done with the matching platform dependencies (the TCK README.adoc was not updated too and contains outdated dependencies).

Best,
Jan

**Comment by sberyozkin** [comment]
@Emily-Jiang so as far as 2.1 is concerned, is it OK to go or the whole ballot is now obsolete ?
To be honest I have no idea why this request from Jan should block a 2.1 release.
