### ISSUE TITLE
Support standard OpenID connect `name`claim

### ISSUE THREAD

**Issue by sberyozkin** [eclipse/microprofile-jwt-auth#316]
The `name` claim is the second claim listed in https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

Right now the specification only mentions a standard `preferred_username` (7th in the list there) as a fallback if  `upn` is missing:

```
**upn (or preferred_username or sub)**

    MP-JWT "upn" claim is the user principal name in the java.security.Principal interface, and is the caller principal name in jakarta.security.enterprise.identitystore.IdentityStore. If this claim is missing, fallback to the ["preferred_username", OIDC Section 5.1](http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) should be attempted, and if that claim is missing, fallback to the "sub" claim should be used.
```

So when someone sends an ID token which has `name`, `sub` but no `preferred_username` issued by Google or Auth0 etc as a bearer token then `JsonWebToken.getName()` gives `sub`, if this MP JWT endpoint uses it to greet the user, we'll get something like `Hello,12345678`. 
`sub` is just a unique identifier, some number, hex sequence, etc, it can't really be used usefully as a principal name. 

The quoted text above should be adapted to have `name` as the fallback preferred to `sub`:

```
**upn (or preferred_username or sub)**

    MP-JWT "upn" claim is the user principal name in the java.security.Principal interface, and is the caller principal name in jakarta.security.enterprise.identitystore.IdentityStore. If this claim is missing, fallback to the ["preferred_username", OIDC Section 5.1](http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) should be attempted, **if the "preferred_username" claim is missing then fallback to the "name" claim should be used, and if the "name" claim is missing,** fallback to the "sub" claim should be used.
```
 
Note this text has `should be` everywhere, not `must be`, so it is not guaranteed to be portable, it is not TCK enforced.
I think, for all the practical/portability purposes, preferring `name` as the 2nd to last fallback, before the final `sub` fallback, is safe and can be done for MP JWT 2.1.1.

@teddyjtorres @dblevins @rdebusscher, do you agree it is good to be fixed for 2.1.1 ?

**Comment by rdebusscher** [comment]
That is a good idea, except that it must be enforced (in the next major version)

It doesn't make sense to add something to the spec which is not required and not even checked by the TCK.  This means that implementors will completely ignore it and thus have no benefit at all for spec users.

In fact, all optional functionality weakens the specification, makes the spec less attractive, and promotes implementation differences and thus incompatibility.  Just the opposite of what a specification should do.

As a person, you also don't want to go to your car dealer and read 'this car might have an entertainment system or might not'.

**Comment by sberyozkin** [comment]
Thanks @rdebusscher, re that text, it is in th3 spec since 1.0 AFAIK, but in any case, after thinking about it for awhile I'm considering to close this issue as it does introduce a breaking change, while it is not enforced,  someone can rely on the `sub` at the last fallback, instead of `name`
