### ISSUE TITLE
Should claims be non-binding

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-jwt-auth#32]
I suspect that the Claim qualifier should be nonbinding. https://docs.jboss.org/cdi/api/1.0-SP2/javax/enterprise/util/Nonbinding.html

Basically, the current impl requires registering beans of each claim type to satisfy injection points.  By making the attributes nonbinding, you can satisfy in a single producer method.

**Comment by starksm64** [comment]
It was seemingly an issue when we were trying to only use @RequestScoped values since such producer methods cannot have an InjectionPoint argument. It is probably better to have non-binding claims.

**Comment by Emily-Jiang** [comment]
+1

**Comment by rmannibucau** [comment]
Should pby be binding since it allows a faster runtime without workaround and request scope constraint is random for these beans and should be removed which is backward compat.
