### ISSUE TITLE
Which attribute takes precedence?

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-jwt-auth#34]
The current usage of Claim allows for an ambiguity:

```java
@Inject
@Claim(name="myname",standard=Claims.sub)
private String myClaim;
```

In this situation, which claim should be searched for, or is there an error thrown?

**Comment by starksm64** [comment]
The enum based claim should take priority in this circumstance, or it should be an error.

**Comment by johnament** [comment]
Does it maybe make more sense to have a `@Claim` and `@NonstandardClaim` as two different qualifiers?  One taking a `String` and the other taking an `enum`.

**Comment by starksm64** [comment]
I'm not for that change at this point. This can be brought up for discussion post the 1.0 API freeze, but it is not something I want to try to squeeze in at the last minute.

**Comment by johnament** [comment]
I think we need to clarify something for 1.0.  The spec's a bit light in this area.  I think for 1.0 we should indicate that it's not supported and a deployment exception is thrown.

**Comment by starksm64** [comment]
That is fine.

**Comment by starksm64** [comment]
The spec states that MP-JWT implementations are required to throw a `DeploymentException` when detecting the ambiguous use of a @Claim qualifier that includes inconsistent non-default values for both the value and standard elements
