### ISSUE TITLE
Why isn't ITokenParser in the API?

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-jwt-auth#35]
It seems weird to me that for TCK purposes only we have to implement a `ITokenParser`.  Why not just put this class in the API and look it up via CDI injection?  End users may find this useful as well.

**Comment by starksm64** [comment]
Originally this was in the API via a ServiceLoader pattern. If there is agreement on moving back that is fine.

**Comment by johnament** [comment]
Ok, so I wanted to wait until I thought I had a decent grasp on how the TCK is using this interface.

It looks like these are implementation details.  You're supplying me a public key and a private key as a part of the TCK. Its up to me to configure Hammock to use them to ensure that the JWTs are properly signed.  

If I look at some of the other tests in there, e.g. `TestTokenClaimTypesTest` and `InvalidTokenTest` I think they can be consolidated.

For one, we shouldn't have any tests that aren't executed within Arquillian.  You're presuming that you can bootstrap the token parser independent, but I need to configure the token parser and rely on CDI for dependency injection.  

As far as this interface goes.  If you want to test it explicitly it needs to be in the API.  Otherwise its only use is within the TCK, not spec mandated.

**Comment by starksm64** [comment]
For 1.0 I was not wanting to test the IToken interface itself as it has not been adequately discussed that the signature is how implementors wanted to deal with the validation context of the token.

Ok, I'll update the tests to use Arquillian and fallback to trying a CDI.current().select(IToken.class).get() call if there is no service provider.

**Comment by johnament** [comment]
I'm not sure that changing the tests at this point is the right thing to do.

It seems to me what's missing is a test that validates JWT (and invalid JWT) that is run as a part of sending the JWT over the wire.  Maybe we need to define an HTTP response code (401?) when the JWT is invalid?

**Comment by starksm64** [comment]
There are a few tests in this area in the InvalidTokenTest.java, so it is a question of verifying that there is sufficient coverage. The ITokenParser based tests are the only ones that cover the complete set of expected types from standard claims. These tests could be be moved into JAX-RS wrapped tests and run in the target container.

**Comment by starksm64** [comment]
We have left the ITokenParser in the tck along with the related tests for 1.0. Moving this to the API in some form is left for 1.1.

**Comment by starksm64** [comment]
After discussing this, the use of the ITokenParser is an implementation issue in the TCK that is redundantly covered by other JAX-RS based tests. The original motivation for having tests that validated an implementation's parsing of the MP-JWT token was to allow for isolation of that testing. Since there is no real user oriented usecase for parsing the MP-JWT token, we are going to drop this issue and remove the related TCK tests.
