### ISSUE TITLE
Finite list of supported injection points

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-jwt-auth#36]
Looking between the spec and the tck, its not clear to me what the actual list of types supported.  If you look, the MP config spec lists this as a finite way, as well as how to register custom types.

**Comment by starksm64** [comment]
The set of valid claim types is the org.eclipse.microprofile.jwt.Claims.type + the JSON-P types for custom claims: JsonValue.TRUE/FALSE, JsonString, JsonNumber, JsonArray, JsonObject.
I'll add a clarifying sentence to this effect in the spec.

**Comment by johnament** [comment]
well that's not good.  There's this line `UNKNOWN("A catch all for any unknown claim", Object.class);` which basically makes everything a valid type.

**Comment by starksm64** [comment]
Ok, excluding UNKNOWN which is just a place holder for a custom claim

**Comment by starksm64** [comment]
The 
Custom claims not handled by the Claims enum are required to be valid JSON-P `javax.json.JsonValue` subtypes. The
current complete set of valid claim types is therfore, (excluding the invalid Claims.UNKNOWN Void type):
* java.lang.String
* java.lang.Long
* java.lang.Boolean
* java.util.Set<java.lang.String>
* javax.json.JsonValue.TRUE/FALSE
* javax.json.JsonString
* javax.json.JsonNumber
* javax.json.JsonArray
* javax.json.JsonObject

**Comment by johnament** [comment]
one of the tests requires `String[]`

**Comment by starksm64** [comment]
I see the old "roles" claim using that. Is that what your referring to? It's not tested and just needs to be removed.

**Comment by johnament** [comment]
Ok, I must have had an older version locally.

So I think I saw what you're trying to do.  Assuming I start from my JWT in the form of `javax.json.JsonObject` then the return value is either the result of the underlying JsonValue of that attribute, or a minimal conversion (e.g. JsonNumber -> long).  I'm assuming I'll have to throw an exception if I looked for an attribute of the wrong type.

**Comment by starksm64** [comment]
Correct.

**Comment by johnament** [comment]
Then I don't understand why `JsonValuejectionEndpoint.aud` is expecting a `JsonArray`.  The input type is a string type, I would expect that its an array type.

**Comment by johnament** [comment]
Another fishy one.  `JsonValuejectionEndpoint.rawToken`, `raw_token` as far as I know isn't actually in the JSON payload, so I don't get why this would be a valid `JsonString` type.

**Comment by johnament** [comment]
Yay fun times.

https://issues.apache.org/jira/browse/CXF-7493 was reported due to the TCK trying to send over a `List<Long>` and `List<Double>` as a query param.  As far as I can tell, there is no way to disable specific methods right now in my setup (have to switch to the TCK xml file to do that).

**Comment by starksm64** [comment]
aud is defined as a Set in Claims.aud due to the fact that it's RFC7519 general type is an array of strings or uris.

The raw_token claim is the original bearer token that maps to the JsonWebToken#getRawToken:
raw_token("MP-JWT specific original bearer token", String.class),

**Comment by johnament** [comment]
Yes, I know where `raw_token` is coming from, however I disagree with the notion that it should support a `JsonValue` injection point.  It's not from the JWT per-se, it is the JWT.

**Comment by starksm64** [comment]
We added an accessor to the JsonWebToken to obtain the original raw token and have defined this as a pseudo claim in both the Claims enum and the JsonWebToken default implementation of the getRawToken() accessor. I would argue that any value accessible via JsonWebToken#getClaim(String) should be injected as a json-p type, but if there is an argument against it, let's hear it and we can vote on it.

**Comment by arjantijms** [comment]
@starksm64 @johnament 

Technically as stated the list of supported types seems infinite.

7.1.2 lists:

* javax.json.JsonValue subtypes

Since `JsonValue` is an interface, it says here to support every subtype of that, which can be custom sub types, of which the amount is practically infinite.
