### ISSUE TITLE
Endpoints used in TCK are not necessarily CDI beans

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-jwt-auth#37]
I have an issue with the endpoints listed in the TCK.  

If I look at `UnsecuredPingEndpoint`, `ClaimValueInjectionEndpoint` etc they lack a bean defining annotation.  As a result, these classes are not necessarily CDI managed beans.

There's two ways to solve this.

1. The TCK passes in a valid CDI 1.1 `beans.xml` that includes `bean-discovery-mode="all"`
2. We add a scope annotation, e.g. `@RequestScoped` or `@Dependent` to each class.

Note: this is an issue for Hammock, since Hammock is based on SE mode of CDI, which uses slightly different discovery rules.

**Comment by starksm64** [comment]
All tests do have a beans.xml, but it is empty, so it would be easy to update it to include the bean-discovery-mode="all"

**Comment by johnament** [comment]
Sounds good to me.

**Comment by johnament** [comment]
Ok, now that the rest issue is resolved, this is more of an issue.

I just looked, because there's no scope resteasy is behaving different than other JAX-RS impls.  Resteasy specifically makes [root resources request scoped when no scope present](http://docs.jboss.org/resteasy/docs/3.0.2.Final/userguide/html/CDI.html) but CXF does not.  The behavior is not defined by the spec.

**Comment by starksm64** [comment]
Try the latest update that sets request scoping explicitly.

**Comment by johnament** [comment]
Agreed.
