### ISSUE TITLE
Client used in tests does not register any providers

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-jwt-auth#38]
The JAX-RS client used in the tests does not register any providers.  I believe you may be relying on resteasy specific behavior where providers are automatically registered.  However, I don't believe that's a requirement of the [JAX-RS Client API](https://github.com/jax-rs/spec/blob/master/chapters/clientapi.tex).  Don't forget that since your tests run as client, they are always running outside the server.

**Comment by starksm64** [comment]
You have to provide a JAX-RS client implementation as part of the test harness. It is describe with a comment in the example skeleton pom.xml with a callout on the topic:

        <4>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <version>3.1.1.Final</version>
        </dependency>

<4> The TCK unit tests make use of the JAX-RS client API, but do not provide an
implementation, so your TCK harness artifact must specify what implementation to use.
Here the Resteasy implementation is being specified.

**Comment by johnament** [comment]
Ok, sorry I wasn't clear then.

The Provider I'm referring to is the JAX-RS Provider, which is the base interface for `MessageBodyReader/Writer`, `Feature`, etc.  The automatic registration of these providers are handled on the server, which is as per the JAX-RS spec.  However, the Client API does not require automatic registration.  Based on the few people I spoke with it wasn't clear why they were separated.  But my understanding is that there is no automatic registration of providers on the client and no requirement to do so.  RestEasy does do this under some circumstances (from what I remember it has the notion of default providers which always get registered).

If you look, the Health TCK worked around this [with SimpleHttp.Response](https://github.com/eclipse/microprofile-health/blob/master/tck/src/main/java/org/eclipse/microprofile/health/tck/SimpleHttp.java#L104).  I'm not opposed to keeping JAX-RS client, however it won't work the way you're using it.  So we'd have to do one of the following:

- The TCK Provides a provider that wraps JSON spec
- The TCK reads a String body and manually parses it from the JSON spec
- The TCK requires an `@ArquillianResource Client` that is configured w/ the necessary providers
- Use a tool like Apache Httpclient
- Use a tool like Rest Assured

**Comment by starksm64** [comment]
Then why not simply move the rest-easy dependency into the TCK and drop the requirement that the tck harness provides it. The rest-easy dependency that enables the json provider is:
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-json-p-provider</artifactId>
            <version>3.0.6.Final</version>
        </dependency>

Since the tests only use the standard JAX-RS client api, I can't see how it would impact the MP-JWT implementation under test to have a specific client.

**Comment by johnament** [comment]
That's the dependency for JSON-P, however it is registered on the client side using resteasy specific behavior.  

https://github.com/resteasy/Resteasy/blob/master/providers/json-p-ee7/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
https://github.com/resteasy/Resteasy/blob/master/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/RegisterBuiltin.java#L23
https://github.com/resteasy/Resteasy/blob/master/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java#L361

In my case, CXF has to come along so you'd be trying to override my JAX-RS dependency (remember, its not a requirement of MP that its a remote server, it could be embedded)

**Comment by starksm64** [comment]
Well that is a gaping hole in the JAX-RS client spec. The easiest thing to do is just to parse the json reply in the test client.

**Comment by starksm64** [comment]
The client tests have been updated to parse a string response instead of requiring a json-p provider.
