### ISSUE TITLE
Mapped Roles

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-jwt-auth#39]
I see the TCK has the notion of mapped roles.  I thought I had it until I saw this test:

```java
    /**
     * This endpoint requires a role that is mapped to the group1 role
     * @return principal name
     */
    @GET
    @Path("/needsGroup1Mapping")
    @RolesAllowed("Group1MappedRole")
    public String needsGroup1Mapping(@Context SecurityContext sec) {
        Principal user = sec.getUserPrincipal();
        sec.isUserInRole("group1");
        return user.getName();
    }
```

I don't see any roles mentioned in the JWT called `Group1MappedRole` so I have no idea how this role is mapped to the user.   Also, for the scope of processing roles, I'm ignoring the object `customObject` is that correct?

**Comment by starksm64** [comment]
This test is about needing to map from a group1 assigned to the JWT to an application level role Group1MappedRole. The group to role mapping notion in Java EE is described here:
https://docs.oracle.com/javaee/7/tutorial/security-intro005.htm#BNBXJ

The only claim that carries any information about the authorization is the "groups" claim, so yet, the customObject claim has no effect on the roles.

**Comment by johnament** [comment]
Unfortunately, I don't see how that answers my question.  Where is the word `Group1MappedRole` coming from?

**Comment by starksm64** [comment]
Group1MappedRole is the application defined role. That is simply what the developer chose as the application level role. The container has to provide a mapping from the "group1" group from the "groups" claim to a Group1MappedRole assigned to the authenticated principal. This will require some additional authorization/role mapping step beyond the authentication of the JWT.

**Comment by johnament** [comment]
How is the application defining this role?

It sounds like this shouldn't be a MP TCK test.

**Comment by starksm64** [comment]
The app has defined the role via the @RolesAllowed("Group1MappedRole") constraint on the method you showed. This is a requirement that we discussed early on.

**Comment by johnament** [comment]
I get that the role is defined on the method.  What is not clear is how you're going from the JWT's contents to the user having that role.  That is completely unclear from the scope of the JWT spec.

**Comment by starksm64** [comment]
Ok, since this behavior is really defined for web profile and higher, 
I'll classify the test using a new ee-security-optional that will not be included in the base MP-JWT tests.

**Comment by johnament** [comment]
Scott, I'm not trying to be a pain, I'm just trying to understand what you're talking about.  It could be that there's a step missing with the TCK that I'm just blind to.

Are you referring to this mapping?

```xml
    <security-role-mapping>
        <role-name>Admin</role-name>
        <group-name>Director</group-name>
    </security-role-mapping>
```

And expecting that an entry that maps group name `group1` into role `Group1MappedRole` is present somewhere?  If so, really at the bottom of this is you're just missing an instruction "you need to add this mapping..."

**Comment by starksm64** [comment]
Yes, that is one example of the mapping one needs to do via a container specific descriptor. 
I can certainly add that to the TCK readme instructions, but you are right that this is outside of the scope of the base MP 1.2 API feature set we are importing from Java EE 7.
