### ISSUE TITLE
Clarification on Claim Deployment Exception

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-jwt-auth#40]
"MP-JWT implementation are required to throw a DeploymentException when detecting the ambiguous use of a @Claim qualifier that includes inconsistent non-default values for both the value and standard elements as is the case shown here:

```
> @ApplicationScoped
> public class MyEndpoint {
>     @Inject
>     @Claim(value="exp", standard=Claims.iat)
>     private Long timeClaim;
> ...
> }
```

Do you mean value and standard cannot be used together?

**Comment by starksm64** [comment]
They cannot be used in an ambiguous ways, yes. They can be specified redundantly, but they cannot refer to different claims.

**Comment by johnament** [comment]
@starksm64 so you're saying that this is valid?

```
@Inject
@Claim(value="iat", standard=Claims.iat)
private Long timeClaim;
```

**Comment by starksm64** [comment]
Yes, I don't see why it should fail.
