### ISSUE TITLE
`@ApplicationScoped` beans may use `@Claim ClaimValue` injection

### ISSUE THREAD

**Issue by dblevins** [eclipse/microprofile-jwt-auth#45]
We have no tests that show an `@ApplicationScoped` bean using `@Claim ClaimValue` injection.

This is supported and should be tested

**Comment by arjantijms** [comment]
@dblevins 

I was surprised about this, as `ClaimValue` looks like a standard wrapper to allow a request scoped injection, but the MP-JWT spec doesn't say anything about this.

There's only 7.1.2 that says:

> This specification requires support for injection of claims from the current JsonWebToken using the org.eclipse.microprofile.jwt.Claim qualifier: [code] with @Dependent scoping.

Where is it written that an `@ApplicationScoped` bean using `@Claim ClaimValue` injection is supported?

**Comment by arjantijms** [comment]
@dblevins small ping ;)

**Comment by arjantijms** [comment]
@dblevins Another small ping ;)

**Comment by starksm64** [comment]
7.1.2 is what implies that this should be supported. We went back and forth with regard to request vs dependent scoping of values and ended up settling on dependent scoping, so any inconsistencies should be clarified in 1.1 release.

**Comment by rmannibucau** [comment]
+1 to support AppScoped injection of claimvalues - otherwise the api is useless by itself and user will need to take care himself to write a wrapper for its JWT to have the right scope without bad performances.

**Comment by struberg** [comment]
+1 as well. Actually it should be possible to inject it almost everywhere. We have CDI NormalScoping proxies to deal with invariances.

**Comment by arjantijms** [comment]
Another mention of this issue: https://github.com/payara/Payara/issues/2742#issuecomment-391673838

**Comment by sberyozkin** [comment]
Hi All, I'll add a TCK test which verifies it works for ApplicationScoped beans

**Comment by sberyozkin** [comment]
I've opened a draft PR at #180.
