### ISSUE TITLE
AppScopedTest doesn't work

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-jwt-auth#46]
Was trying to figure out the remaining TCK issues in Hammock.  I found that `AppScopedTest` isn't working.  

https://github.com/eclipse/microprofile-jwt-auth/blob/master/tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/AppScopedTest.java#L38

It doesn't extend from `Arquillian` so it's not a valid CDI test, the CDI container never boots.

**Comment by sberyozkin** [comment]
Hi John, @johnament, this test may have been intentionally left out, and it looks incorrect now to me, i.e, we definitely expect `@ApplicationScoped` beans working correctly with the RequestScoped tokens.
I've marked #45 for `JWT 1.2` - I'll fix it by just copying one the tests which would run against an ApplicationScoped endpoint
Cheers !
