### ISSUE TITLE
Unclear how to validate JWTs using the resources provided

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-jwt-auth#47]
https://github.com/eclipse/microprofile-jwt-auth/tree/master/tck#tck-resource-files-and-information lists a bunch of resources provided.  I'm attempting to make `InvalidTokenTest` pass.  When I enable token validation, since I'm using Nimbus Jose, I need to build a JWKSet.  Its not clear how to translate the resources you're providing into that JWKSet based on the instructions available.

**Comment by starksm64** [comment]
I have added a number of internal debug tests to the org.eclipse.microprofile.jwt.tck.parsing.DebugTest class that illustrate setting up the Nimbus library to validate the test JWT. See:

DebugTest.testNimbusExpGrace
DebugTest.testNimbusFailExpired
DebugTest.testNimbusFailIssuer
DebugTest.testNimbusFailJustExpired
DebugTest.testNimbusFailSignature
DebugTest.testNimbusValidation

A reference to this has been added to the TCK README.adoc as well.
