### ISSUE TITLE
Clarify request scoped current caller and logout/login mid-request

### ISSUE THREAD

**Issue by arjantijms** [eclipse/microprofile-jwt-auth#49]
The MP-JWT spec 1.0 currently states in 7.1.1:

> An MP-JWT implementation must support the injection of the currently authenticated caller as a
> JsonWebToken with @RequestScoped scoping

However, a caller can logout in the midst of a request (i.e. by calling `HttpServletRequest#logout`),  and even login again (i.e. by calling `HttpServletRequest#authenticate` or `SecurityContext#authenticate`).

An `@RequestScoped` JsonWebToken would have to be destroyed *immediately* after a logout in the middle of a request, but this requirement is not clear and the TCK does not seem to test for this. This runs the risk that some implementations will keep using the JsonWebToken to represent a caller, which is currently not the actual authenticated caller anymore.

**Comment by heiko-braun** [comment]
Would it be better to inject a proxy for retrieval upon demand, rather then the token itself? This could ensure that no stale tokens linger and the backing implementation get's a chance to handle these situations.

I.e the aforementioned proxy could be a `Supplier< JsonWebToken >` or something along these lines.

**Comment by arjantijms** [comment]
>Would it be better to inject a proxy for retrieval upon demand, rather then the token itself

Probably would have been better indeed, but it's currently already being specified as being request scoped.

The claim values theoretically could stay available for the duration of the request, but after the caller logged-out it's application dependent I think whether these are still useful or not.

But one thing about which there can be no doubt is that after a log-out mid request the caller name and groups in the injected `JsonWebToken` should NOT be used to make authentication or authorisation decisions anymore.

I have a feeling that the entire concept of logging out mid-request may have been somewhat overlooked.

**Comment by sberyozkin** [comment]
Hi @arjantijms 

> I have a feeling that the entire concept of logging out mid-request may have been somewhat overlooked.

I'm really not sure why we should look into this use case where someone would write a code such as `logout` following by `authenticate`. MP JWT can't cover all the strange variations IMHO

**Comment by arjantijms** [comment]
> MP JWT can't cover all the strange variations 

I'm not convinced that "Logging out" is really a strange variation. Note that the issue's description talks about the scope of the token and the logout action itself. NOT necessarily about authenticating again.

Authenticating again is something that *could* be done. That action too is not strange, as it's often used to implement `runAs` functionality, but if it's confusing forget about that.

The problem here is that after a logout, the token is still specified to be valid for the remainder of the request.
