### ISSUE TITLE
Fix group Ids/artifact Ids

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-jwt-auth#5]
Group ID should be in the format of `org.eclipse.microprofile.jwt` (or maybe `.jwt.auth`?).  Please fix the group Ids to match.  Please also fix the artifact Ids to line up with other specs.

**Comment by starksm64** [comment]
The api style was based on some version of the config spec usage, but I have updated the conventions to be consistent with the current config project.

**Comment by starksm64** [comment]
This is addressed in #11

**Comment by dblevins** [comment]
We can use the Nimbus Library for creating JWTs for the TCK.

 - https://connect2id.com/products/nimbus-jose-jwt

**Comment by starksm64** [comment]
This has been incorporated into the current 1.0-RC3 candidate release.
