### ISSUE TITLE
TCK swaps TestNG 'expected' and 'actual' outcomes

### ISSUE THREAD

**Issue by arjantijms** [eclipse/microprofile-jwt-auth#52]
Through the entire TCK, the `expected` and `actual` outcomes in an assertion are swapped.

E.g. see

```java
Assert.assertEquals(HttpURLConnection.HTTP_OK, response.getStatus());
```

The first parameter should be the actual outcome, while the second should be the expected one. See

* https://jitpack.io/com/github/cbeust/testng/master-6.13.1-gbf99034-6/javadoc/org/testng/Assert.html#assertEquals-boolean:A-boolean:A-

But as can be seen, the TCK reverses that.

As a result, output is now printed as:

> ServletTest>Arquillian.run:164->getServletPrincipalClass:101 expected [500] but found [200]

This is clearly not correct. 200 is expected while 500 is the actual outcome in the example.

**Comment by starksm64** [comment]
Fixed by duplicate #64 PR.
