### ISSUE TITLE
Slightly reformat the package-info.java files for the javadoc

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile-jwt-auth#53]
Currently, the generated javadoc for JWT has the Description field running together.  I think a simple re-format of the package-info.java files would make this more readable.

The generated Description for the auth package looks like this:
`Metadata for JWT RBAC for Microprofile This package contains supporting metadata classes: LoginConfig: an annotation that is used by a JAX-RS Application to define the authentication method and associated security realm.`

And, the generated Description for the jwt package looks like this:
`Interoperable JWT RBAC for Microprofile This package contains the primary interfaces and support classes for the JSON Web Tokens(JWT) for role based access control(RBAC) of MicroProfile microservice endpoints.`

**Comment by starksm64** [comment]
The formatting has been fixed.
