### ISSUE TITLE
Spec pom.xml needs updates for proper pdf and html generation

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile-jwt-auth#54]
Just a gentle reminder that since this component has not used the updated release process yet, you will need updates to your spec's pom.xml file for proper generation of the pdf and html.  We found a couple of hiccups with components during the MP 1.3 release, so I'm creating a couple of Issues as reminders.  You can reference the Config component as an example of proper usage.

**Comment by starksm64** [comment]
Done.
