### ISSUE TITLE
Define a standard Cookie for holding the MP-JWT token

### ISSUE THREAD

**Issue by starksm64** [eclipse/microprofile-jwt-auth#55]
There is a desire to define the use of a standard cookie name,value for interop between applications as described in:
https://blog.angular-university.io/angular-jwt-authentication/

and MP microservices.

**Comment by hrstoyanov** [comment]
Here is another good discussion on storing JWT tokens in cookies:
https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage

When is MP-JWT 1.1 due?

**Comment by starksm64** [comment]
MP-JWT 1.1 will align with the MP 1.4 release which is due in just under 6 weeks, May 8.

**Comment by starksm64** [comment]
Discussion thread:
https://groups.google.com/forum/#!topic/microprofile/M4Nt7UGRnDI

**Comment by starksm64** [comment]
Added a "Recommendations for Cookies" section

**Comment by sc3n** [comment]
@starksm64 can you please advise whether passing jwts as cookies might be considered in upcoming releases?

See also https://github.com/eclipse/microprofile-jwt-auth/blob/961ebac1ec28f05d9abca81e157e09dd7f5c6edb/spec/src/main/asciidoc/future-directions.asciidoc#passing-jwts-as-cookies
