### ISSUE TITLE
Requirements for supporting JSON-B

### ISSUE THREAD

**Issue by starksm64** [eclipse/microprofile-jwt-auth#56]
Review what changes would be needed to support the use of JSON-B with JsonWebToken and its claim values.

**Comment by keilw** [comment]
That could be challenging. Right now, especially the TCK doesn't even support JSON-P because the Nimbus JWT/Jose library brings its own JSON framework other than JSON-P standards.

**Comment by sberyozkin** [comment]
@starksm64 Hi Scott, Roberto is looking into a generic Conversion support so we'll let users eventually use JSONB inside their custom converters if they prefer
