### ISSUE TITLE
Define minimum useful support for JWE

### ISSUE THREAD

**Issue by starksm64** [eclipse/microprofile-jwt-auth#58]
Would like to see if we can have interoperable encrypted JWT, maybe some minimum support requirement similar to OIDC, http://openid.net/specs/openid-connect-core-1_0.html#Encryption

JWE: https://tools.ietf.org/html/draft-ietf-jose-json-web-encryption-40

**Comment by starksm64** [comment]
JWK and headers need to be looked at.

**Comment by sberyozkin** [comment]
You are right, but it will mean the private keys manages by the AS will have to be exported into all of RS. Which is probably a key management challenge, though yes, out of scope for MP-JWT :-)

**Comment by sberyozkin** [comment]
I'm wiring the encryption support into the builder API I'm working upon

**Comment by chunlongliang-ibm** [comment]
In addition to JWT API, we should consider to mpJWT configuration to decrypt JWE  for some common and simple scenarios, in particular, the dir ( symmetric key) scenario. Only JWE with 'dir' is supported.
1. The 'dir' alg is much simpler to be processed, and the symmetric key could be defined via mp-config.
2. The 'dir' scenario is also useful given that we now plan to support JWT builder API. If client builds self-signed JWT for downstream service, it is reasonable to assume both should share some secret, which can be used as encryption key.
