### ISSUE TITLE
Don't rely on Keycloak

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-jwt-auth#6]
specific vendor tooling should not be required to use MicroProfile

**Comment by starksm64** [comment]
Why is Keycloak fundamentally different than Google's gson? It is just an open source project that has component libraries that touch on JWT parsing and validation.

Keycloak is not and really could not be a MicroProfile implementation for JWT RBAC, even though it can be a component of such an implementation.

**Comment by starksm64** [comment]
The token dependency parsing is now using the com.nimbusds:nimbus-jose-jwt library.
