### ISSUE TITLE
License not consistent

### ISSUE THREAD

**Issue by jeanouii** [eclipse/microprofile-jwt-auth#60]
Hi,

Some files like beans.xml or arquillian.xml don't have the same header as the Java source files. Is that desire?

Should I create a PR for it?

Thanks
Jean-Louis

**Comment by kwsutter** [comment]
Yes, please.

**Comment by starksm64** [comment]
Did you have a PR for this? I'm not seeing one.

**Comment by jeanouii** [comment]
Looks like it is all fixed now. Sorry for the noise. Can be close now
