### ISSUE TITLE
Configure issuer and public key in vendor-neutral way

### ISSUE THREAD

**Issue by jGauravGupta** [eclipse/microprofile-jwt-auth#62]
Currently following implementation supports the MP-JWT but  issuer and public key configuration way is bit different in each implementation. It would be great, if it can be configured in vendor-neutral way e.g using MP-Config etc.

### Payara
**issuer -** defined in "payara-mp-jwt.properties" which is placed in the classpath root of the application archive
**public key -** the file "publicKey.pem" which is also placed in the classpath root of the application archive

### Liberty
**issuer -** defined in the "mpJwt" tag in "server.xml" which in the placed inside the installed Liberty: [install dir]/wlp/usr/servers/defaultServer/server.xml
**public key -** the file "key.jks" which in the placed inside the installed Liberty: [install dir]/wlp/usr/servers/defaultServer/resources/security/key.jks

### WildFly (Swarm)
**issuer -** defined in "project-default.yml" which is placed in the classpath root of the application archive. This also configures the security system (security domain in JBoss terms) such that all artifacts to support MP-Auth JWT are installed
**public key -** the file "MP-JWT-SIGNER" which is placed in the classpath's META-INF of the application archive.

Ref : https://github.com/javaee-samples/microprofile1.2-samples/tree/master/jwt-auth

**Comment by arjantijms** [comment]
Any comments here?

With users now slowly beginning to try out MP-JWT this seems to be the major thing people struggle with.

**Comment by Emily-Jiang** [comment]
+1 on using MP Config to unite the differences.

**Comment by starksm64** [comment]
Yes, we need a way to enable configuration via MP Config.

**Comment by starksm64** [comment]
Discussion on initial work is here:
https://groups.google.com/forum/#!topic/microprofile/LPe7N5CZqtE

**Comment by starksm64** [comment]
The spec and tests have been updated with support for configuring the signer and optional issuer.
