### ISSUE TITLE
TCK : Missing test for required 'aud' claim

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-jwt-auth#63]
According to the spec, 'aud' claim is required.

A same type of test as for issuer should be foreseen.

**Comment by cghislai** [comment]
According to https://tools.ietf.org/html/rfc7519#section-4.1.3, it is not: `Use of this claim is OPTIONAL.`, however processors must identify themselves in this claim if it is present.
It would be nice indeed to be able configure the container with accepted values, possibly with wildcards/regexp.

**Comment by sberyozkin** [comment]
Looks like the `aud` is not required now so let me close this issue
