### ISSUE TITLE
Need test of injecting a java.security.Principal in addition to JsonWebToken.

### ISSUE THREAD

**Issue by starksm64** [eclipse/microprofile-jwt-auth#68]
As pointed out in this thread:
https://groups.google.com/forum/#!topic/microprofile/BJO50mFZd8w

we should hava a TCK test for both injection of the JsonWebToken interface as well as the java.security.Principal superinterface to ensure both are handled.

**Comment by jGauravGupta** [comment]
Hi @starksm64,
`@Inject java.security.Principal` always returns weld proxy object which is not instance of `JsonWebToken`. But this test validates injected instance for `JsonWebToken`
