### ISSUE TITLE
TCK: Arquillian sometimes generates trailing / when injecting URL and failing the tests

### ISSUE THREAD

**Issue by urbim** [eclipse/microprofile-jwt-auth#71]
In some cases Arquillian generates trailing / when injecting base URL with `@ArquillianResource`.

See: https://github.com/arquillian/arquillian-core/blob/master/container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/enricher/resource/URLResourceProvider.java

`toURL(Servlet servlet)` generates trailing / and `toURL(HTTPContext context)` does not.

This represents a problem in almost all tests, beacuse they contain something similar to:

```java
String uri = baseURL.toExternalForm() + "/endp/verifyInjectedIssuer";
```

When trailing / is present the `uri` is set to something like `http://host:port//endp/verifyInjectedIssuer` (note the two slashes between `port`and `endp`), which yields a 404 when queried and fails the test.

**Comment by arjantijms** [comment]
I encountered the same issue, and solved is as follows. Not entire perfect perhaps and I'm probably missing some edge cases, but could serve as a starting point:

https://github.com/payara/MicroProfile-TCK-Runners/blob/master/MicroProfile-JWT-Auth/payara-jwt-auth-arquillian-extension/src/main/java/fish/payara/microprofile/jwtauth/tck/URLResourceProvider.java

**Comment by starksm64** [comment]
This is using the 1.1.13.Final version of Arquillian? I never saw this while running the TCK so I'm curious where the error is coming from. Is it the JAX-RS client layer that is failing on the URL?

**Comment by starksm64** [comment]
So this appears to have been overlooked in my testing as the RestEasy JAX-RS client library handles the existence of double slashes transparently. The tests should just be updated to avoid the extra slash.
