### ISSUE TITLE
Could the TCK use auth0 instead of Nimbus JWT?

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-jwt-auth#72]
While there is nothing wrong with Nimbus Jose JWT, it is quite intrusive bringing its own JSON processing library (minidev). The KumuluzEE implementation uses auth0 java-jwt and e.g.:
[JWTPrincipal](https://github.com/kumuluz/kumuluzee-jwt-auth/blob/master/src/main/java/com/kumuluz/ee/jwt/auth/principal/JWTPrincipal.java) demonstrates, Auth0 works perfectly fine with the JSON-P instead of its own library.

**Comment by rdebusscher** [comment]
As it is just used in the TCK, and thus every implementation can use whatever library it wants, what is the point in changing it then (except when the quality isn't good enough)

**Comment by keilw** [comment]
It would reduce the overhead of multiple different JSON libraries, but it is not such a huge priority compared to getting the Parent POM in line so this TCK and others behave more consistently.

**Comment by mkouba** [comment]
By the way, `nimbus-jose-jwt` is using Maven version ranges and if I clone the repo and run `mvn clean install` I get:
> [ERROR] Failed to execute goal on project microprofile-jwt-auth-tck: Could not resolve dependencies for project org.eclipse.microprofile.jwt:microprofile-jwt-auth-tck:jar:1.1-SNAPSHOT: Could not find artifact commons-io:commons-io:jar:2.7-SNAPSHOT -> [Help 1]

I'm not sure if there's something wrong with my local config though...

**Comment by heiko-braun** [comment]
@mkouba I encountered the same issue. I think if we bring in a dep into an eclipse project it would be to avoid this. Unfortunately the only way to handle seems to changes to the nimbus-jose-jwt project itself.

**Comment by rdebusscher** [comment]
You can fix the version of nimbus-jose-jwt by defining it within the
dependency management section of Maven

But it is indeed an issue that nimbus-jose-jwt works with ranges.

**Comment by sberyozkin** [comment]
Hi All, would you object if we have Jose4J for the tests ? (We use it internally, but it is not really relevant, Jose4j is a trusted and slim library, IMHO it can definitely produce a more compact (test) JWT generation API, telling after replacing an internal test Nimbus JWT code with the equivalent Jose4j one)

**Comment by rdebusscher** [comment]
Jose4J is a bit more complete in supported features (like claim checks) but API is not that clear as Nimbus JWT. ( personal opinion maybe)
But I don't like the usages of artifact version ranges in Nimbus JWT.

**Comment by sberyozkin** [comment]
@rdebusscher sure, it is only to support the TCK (use an independent tool to generate a token) as we'll go ahead with out generation API anyway, so whatever is simpler from that angle will should work :-). I might give it a go and create PR later and will CC you.

**Comment by sberyozkin** [comment]
Working on the PR to update it to jose4j
