### ISSUE TITLE
Clarify the interaction between @RolesAllowed, @DenyAll, @PermitAll

### ISSUE THREAD

**Issue by starksm64** [eclipse/microprofile-jwt-auth#74]
We don't explicitly define the precedence and interaction between these annotations, especially when combined at class and method level. We also don't mention the use of @DenyAll, @PermitAll. This needs to be clarified in the spec.

**Comment by Ladicek** [comment]
I think the behavior of these annotations should mirror the EJB security behavior as closely as possible. That is, only one of them can be used on the class level and on the method level (if not, it's an error), and if there is an annotation both on the method and on the class, the method one takes precedence.

**Comment by starksm64** [comment]
Added a "Using the Common Security Annotations for the Java Platform" section that clarifies that this behavior should be as described in section 2.12 "PermitAll, DenyAll and RolesAllowed
interactions" of the JSR-250 spec.

**Comment by Ladicek** [comment]
I can't find a commit with this change, so I figured I'd rather ask: could/should we also mention sections 2.9, 2.10 and 2.11? Because otherwise we don't define the intended behavior at all.
