### ISSUE TITLE
declarative security on JAX-RS resources is unspecified

### ISSUE THREAD

**Issue by Ladicek** [eclipse/microprofile-jwt-auth#81]
The MP JWT spec refers to some of the security annotations (`@DenyAll` and `@RolesAllowed`) a couple of times, in a way that implies that these annotations can be used for achieving declarative security on JAX-RS resources. However, that is totally unspecified, both in JAX-RS itself and MP JWT.

I believe this needs to be specified somewhere. Not sure where exactly, but my understanding is that even JAX-RS 2.1 doesn't define declarative security. I also believe this needs to mirror the EJB declarative security as closely as possible, because principle of least surprise.

(Question: what would happen today with an MP implementation that also supports EJB, in an application where a JAX-RS resource is also a session bean? The MP JWT spec does define some additional requirements for such implementations, so this would be a concern as well.)

**Comment by Ladicek** [comment]
Here's a consequence of this being unspecified: the WildFly Swarm MP JWT fraction implements declarative security by translation to `<security-constraint>`s in `web.xml`. That, however, can't possibly cover all of JAX-RS: https://issues.jboss.org/browse/SWARM-1955

**Comment by Ladicek** [comment]
CC @starksm64

**Comment by Ladicek** [comment]
Probably related to #74

**Comment by starksm64** [comment]
Right, #74 is the task that was to clarify this underspecified extension of the security annotations to JAX-RS endpoints.

**Comment by Ladicek** [comment]
The title and description of #74 are quite narrow, but if the intent is cover all of declarative security, then we're on the same page :-)
