### ISSUE TITLE
release 1.1

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-jwt-auth#88]
Current master has several fixes compared to last release, would it be possible to have a final version of it?

Thanks,
Romain

**Comment by rmannibucau** [comment]
up?

**Comment by starksm64** [comment]
In progress, will get RC 1.1 out today.

**Comment by rmannibucau** [comment]
Any news? Is there some issues or just the classical time one ;)?

**Comment by starksm64** [comment]
Put out on June 1 2018
