### ISSUE TITLE
TCK should only provide tests

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-jwt-auth#9]
The current TCK seems to assume that you're using Wildfly Swarm or Weld SE.  We should only be providing the tests in the TCK, and allowing the vendors to test with these tests.

**Comment by starksm64** [comment]
We are scheduled to discuss specific vendor profiles, but the Weld SE profile is simply an extension of the Arquillian test environment as some container runtime is needed for CDI based tests. The weld-se profile will be used to test basic parsing and presentation of JWT tokens as JWTPrincipals independent of a complete JWT RBAC implementation.

**Comment by starksm64** [comment]
As of the 1.0-RC1 release, the TCK only provides tests and harness code that MP-JWT implementations can use with an implementation provided TCK harness artifact to run the tokens-se and container profile tests.
