### ISSUE TITLE
Drop or rephrase "When there are multiple JSON Web Keys (JWK) in the JSON Web Key Set (JWKS), the `kid` field  is required in each JWK and incoming JWT being authenticated." requirement

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-jwt-auth#92]
Rational is that it requires either a more precised definition or it can't be done.

1. Concretely the backend can not know there are multiple keys (mp-config doesn't give that info for instance or any key based backend) so it would require another flag to say "fail on missing kid"
2. It is fine to support a default kid (in particular for backward compatibility)

So the goal is fine but requires a flag probably like "<prefix>.kid.required".

**Comment by sberyozkin** [comment]
@rmannibucau Romain, this requirement looks reasonable to me. The backend does know how many JWKs are in the set.

**Comment by sberyozkin** [comment]
@rmannibucau Hi Romain, let me close this one, don't hesitate to reopen please if you think I've missed a point which may be true :-)

**Comment by rmannibucau** [comment]
@sberyozkin the spec is not about the storage logic/how keys are loaded - mp-config abstracts it, therefore the spec can't enforce the presence of any field due to ambiguity. So yes, I assume most of the time kid will be needed but the spec can't decide at its level if it must fail or not. Relaxing the sentence with a should is fine for me but dropping this sentence enables more usages.
