### ISSUE TITLE
Allow for custom authorization header and scheme

### ISSUE THREAD

**Issue by jeanouii** [eclipse/microprofile-jwt-auth#93]
It is very common to use `Authorization` header with `Bearer` scheme.
But there must be more than one JWT and therefor it would be useful to make this configurable even if they default to `Authorization` header and `Bearer` scheme.

As discussed together, this won't go into this release but we should address this issue later.

**Comment by chunlongliang-ibm** [comment]
Many existing applications have header 
Authorization: Token <JWT here>
For example,  https://github.com/gothinkster/realworld/tree/master/api

**Comment by sberyozkin** [comment]
We have 3 properties in `smallrye-jwt` to deal with it:
`smallrye.jwt.token.header`
`smallrye.jwt.token.cookie`
`smallrye.jwt.token.scheme`

The first 2 headers support non `Authorization` headers, the 2nd one - a cookie name if the 1st property is set to `Cookie` and the 3rd one - a custom `Authorization` scheme like `Token`.

We can have:
```
`mp.jwt.token.header`
`mp.jwt.token.cookie`
`mp.jwt.token.scheme`
```

**Comment by vp642** [comment]
+1 to have a token in a cookie. I am working on a project that could have used this feature to make the code shorter.

**Comment by radcortez** [comment]
If it is ok, I'll work on this and try to submit a PR.

**Comment by radcortez** [comment]
I've pushed the spec update in #176. If we are happy with it, I'll write the required TCK tests.

**Comment by sberyozkin** [comment]
#176 introduces support for the cookies and also makes it clear the other headers/schemes can be optionally supported. IMHO it would be better to resolve this issue now and instead open new issues going forrward dedicated to providing a 1st class support for the alternative well known schemes, headers (not just any headers). The spec is enough open enough for the implementers to support whatever they need and will back them up as needed.
